const Map<String, String> appStringsEn = {
  'main.001': 'Shawakel',
  'screens_account_settings_screen.001': 'Saved',
  'screens_account_settings_screen.002': 'Could not save',
  'screens_account_settings_screen.003': 'Missing data',
  'screens_account_settings_screen.004': 'Mismatch',
  'screens_account_settings_screen.005': 'Password too short',
  'screens_account_settings_screen.006': 'Updated',
  'screens_account_settings_screen.007': 'Could not update',
  'screens_account_settings_screen.008': 'Account Settings',
  'screens_account_settings_screen.009': 'Profile',
  'screens_account_settings_screen.010': 'Password',
  'screens_account_settings_screen.011': 'Save changes',
  'screens_account_settings_screen.012': 'Update password',
  'screens_account_settings_screen.013': 'Current password',
  'screens_account_settings_screen.014': 'New password',
  'screens_account_settings_screen.015': 'Update password',
  'screens_account_settings_screen.016': 'Verified account',
  'screens_account_settings_screen.017': 'Unverified account',
  'screens_account_settings_screen.018': 'No phone number',
  'screens_account_settings_screen.019': 'Basic information',
  'screens_account_settings_screen.020': 'Full name',
  'screens_account_settings_screen.021': 'Username',
  'screens_account_settings_screen.022': 'Phone / WhatsApp',
  'screens_account_settings_screen.023': 'Email',
  'screens_account_settings_screen.024': 'Address',
  'screens_account_settings_screen.025': 'Identity & extra details',
  'screens_account_settings_screen.026': 'National ID',
  'screens_account_settings_screen.027': 'Birth date',
  'screens_account_settings_screen.028': 'Referral number',
  'screens_account_settings_screen.029': 'Print logo',
  'screens_account_settings_screen.030': 'A custom logo is saved',
  'screens_account_settings_screen.031': 'No custom logo yet',
  'screens_account_settings_screen.032': 'Upload logo',
  'screens_account_settings_screen.033': 'Delete logo',
  'screens_account_settings_screen.034': 'Could not read file',
  'screens_account_settings_screen.035': 'Uploaded',
  'screens_account_settings_screen.036': 'Could not upload',
  'screens_account_settings_screen.037': 'Deleted',
  'screens_account_settings_screen.038': 'Could not delete',
  'screens_account_verification_screen.001': 'Missing attachments',
  'screens_account_verification_screen.002': 'Submitted successfully',
  'screens_account_verification_screen.003': 'Submission failed',
  'screens_account_verification_screen.004': 'Identity Verification',
  'screens_account_verification_screen.005': 'Verify your account',
  'screens_account_verification_screen.006': 'Under review',
  'screens_account_verification_screen.007': 'Resubmission required',
  'screens_account_verification_screen.008': 'Not verified yet',
  'screens_account_verification_screen.009': 'Required documents',
  'screens_account_verification_screen.010': 'Identity or passport image',
  'screens_account_verification_screen.011': 'Selfie with identity',
  'screens_account_verification_screen.012': 'Additional notes',
  'screens_account_verification_screen.013': 'Submit verification request',
  'screens_account_verification_screen.014': 'Selected',
  'screens_account_verification_screen.015': 'Choose file',
  'screens_admin_card_print_requests_screen.001': 'Card Print Requests',
  'screens_admin_card_print_requests_screen.002': 'Request tracking',
  'screens_admin_card_print_requests_screen.003': 'Status',
  'screens_admin_card_print_requests_screen.004': 'All',
  'screens_admin_card_print_requests_screen.005': 'Pending review',
  'screens_admin_card_print_requests_screen.006': 'Approved',
  'screens_admin_card_print_requests_screen.007': 'Printing',
  'screens_admin_card_print_requests_screen.008': 'Ready',
  'screens_admin_card_print_requests_screen.009': 'Completed',
  'screens_admin_card_print_requests_screen.010': 'Rejected',
  'screens_admin_card_print_requests_screen.011': 'Review',
  'screens_admin_card_print_requests_screen.012': 'Approved',
  'screens_admin_card_print_requests_screen.013': 'Printing',
  'screens_admin_card_print_requests_screen.014': 'Ready',
  'screens_admin_card_print_requests_screen.015': 'Customer',
  'screens_admin_card_print_requests_screen.016': 'Request',
  'screens_admin_card_print_requests_screen.017': 'Type',
  'screens_admin_card_print_requests_screen.018': 'Single use',
  'screens_admin_card_print_requests_screen.019': 'Regular',
  'screens_admin_card_print_requests_screen.020': 'Quantity',
  'screens_admin_card_print_requests_screen.021': 'Value',
  'screens_admin_card_print_requests_screen.022': 'Total',
  'screens_admin_card_print_requests_screen.023': 'Approve',
  'screens_admin_card_print_requests_screen.024': 'Reject',
  'screens_admin_card_print_requests_screen.025': 'Start printing',
  'screens_admin_card_print_requests_screen.026': 'Ready for delivery',
  'screens_admin_card_print_requests_screen.027': 'Complete request',
  'screens_admin_card_print_requests_screen.028': 'Processing...',
  'screens_admin_customers_screen.001': 'Could not load customers',
  'screens_admin_customers_screen.002': 'Missing data',
  'screens_admin_customers_screen.003': 'User created',
  'screens_admin_customers_screen.004': 'Creation failed',
  'screens_admin_customers_screen.005': 'Add new user',
  'screens_admin_customers_screen.006': 'Username',
  'screens_admin_customers_screen.007': 'Full name',
  'screens_admin_customers_screen.008': 'Country code',
  'screens_admin_customers_screen.009': 'WhatsApp',
  'screens_admin_customers_screen.010': 'Cancel',
  'screens_admin_customers_screen.011': 'Saving...',
  'screens_admin_customers_screen.012': 'Create',
  'screens_admin_customers_screen.013': 'Resend WhatsApp credentials',
  'screens_admin_customers_screen.014': 'Cancel',
  'screens_admin_customers_screen.015': 'Send',
  'screens_admin_customers_screen.016': 'Account details resent.',
  'screens_admin_customers_screen.017': 'Customer Management',
  'screens_admin_customers_screen.018': 'Customer Management',
  'screens_admin_customers_screen.019': 'Visible now',
  'screens_admin_customers_screen.020': 'Total in system',
  'screens_admin_customers_screen.021': 'Customers',
  'screens_admin_customers_screen.022': 'Add user',
  'screens_admin_customers_screen.023': 'Search for a customer...',
  'screens_admin_customer_screen.001': 'Resend user details',
  'screens_admin_customer_screen.002': 'Cancel',
  'screens_admin_customer_screen.003': 'Confirm send',
  'screens_admin_customer_screen.004': 'Sent',
  'screens_admin_customer_screen.005': 'Could not send',
  'screens_admin_customer_screen.006': 'Shawakel customer',
  'screens_admin_customer_screen.007': 'Overview',
  'screens_admin_customer_screen.008': 'Transactions',
  'screens_admin_customer_screen.009': 'Management & Fees',
  'screens_admin_customer_screen.010': 'Permissions',
  'screens_admin_customer_screen.011': 'Devices',
  'screens_admin_customer_screen.012': 'Quick actions',
  'screens_admin_customer_screen.013': 'Current balance',
  'screens_admin_customer_screen.014': 'Account status',
  'screens_admin_customer_screen.015': 'Disabled',
  'screens_admin_customer_screen.016': 'Active',
  'screens_admin_customer_screen.017': 'Contact details',
  'screens_admin_customer_screen.018': 'Username',
  'screens_admin_customer_screen.019': 'Full name',
  'screens_admin_customer_screen.020': 'WhatsApp',
  'screens_admin_customer_screen.021': 'Join date',
  'screens_admin_customer_screen.022': 'Basic customer',
  'screens_admin_customer_screen.023': 'Customer transactions',
  'screens_admin_customer_screen.024': 'All',
  'screens_admin_customer_screen.025': 'Near branches',
  'screens_admin_customer_screen.026': 'Outside branches',
  'screens_admin_customer_screen.027': 'No recent transactions.',
  'screens_admin_customer_screen.028': 'Account management & fees',
  'screens_admin_customer_screen.029': 'Verification status',
  'screens_admin_customer_screen.030': 'Restricted member',
  'screens_admin_customer_screen.031': 'Verified member',
  'screens_admin_customer_screen.032': 'Advanced member',
  'screens_admin_customer_screen.033': 'Unverified',
  'screens_admin_customer_screen.034': 'Pending',
  'screens_admin_customer_screen.035': 'Verified / active',
  'screens_admin_customer_screen.036': 'Rejected',
  'screens_admin_customer_screen.037': 'Account role',
  'screens_admin_customer_screen.038': 'Basic user',
  'screens_admin_customer_screen.039': 'Support team',
  'screens_admin_customer_screen.040': 'Technical admin',
  'screens_admin_customer_screen.041': 'Printing debt limit (₪)',
  'screens_admin_customer_screen.042': 'Custom fees for this customer (%)',
  'screens_admin_customer_screen.043': 'Save changes',
  'screens_admin_customer_screen.044': 'Top-up',
  'screens_admin_customer_screen.045': 'Withdraw',
  'screens_admin_customer_screen.046': 'Transfer',
  'screens_admin_customer_screen.047': 'Redeem',
  'screens_admin_customer_screen.048': 'Resell',
  'screens_admin_customer_screen.049': 'Print request',
  'screens_admin_customer_screen.050': 'Card & admin permissions',
  'screens_admin_customer_screen.051': 'Issue balance cards',
  'screens_admin_customer_screen.052': 'Request card printing',
  'screens_admin_customer_screen.053': 'Issue sub-shekel cards',
  'screens_admin_customer_screen.054': 'Issue high-value cards',
  'screens_admin_customer_screen.055': 'Resell used cards',
  'screens_admin_customer_screen.056': 'Review print requests',
  'screens_admin_customer_screen.057': 'Prepare and print requests',
  'screens_admin_customer_screen.058': 'Finalize and deliver requests',
  'screens_admin_customer_screen.059': 'Manage other users',
  'screens_admin_customer_screen.060': 'Device policy & access points',
  'screens_admin_customer_screen.061': 'Maximum allowed devices',
  'screens_admin_customer_screen.062': 'Update device policy',
  'screens_admin_customer_screen.063': 'Active devices',
  'screens_admin_customer_screen.064': 'Unknown device',
  'screens_admin_dashboard_screen.001': 'Admin Center',
  'screens_admin_dashboard_screen.002': 'Quick Admin Hub',
  'screens_admin_device_requests_screen.001': 'Device Requests',
  'screens_admin_device_requests_screen.002': 'Device requests',
  'screens_admin_device_requests_screen.003': 'Pending requests',
  'screens_admin_locations_screen.001': 'Could not load branches',
  'screens_admin_locations_screen.002': 'Missing data',
  'screens_admin_locations_screen.003': 'Could not save',
  'screens_admin_locations_screen.004': 'Add branch',
  'screens_admin_locations_screen.005': 'Edit branch',
  'screens_admin_locations_screen.006': 'Branch name',
  'screens_admin_locations_screen.007': 'Address',
  'screens_admin_locations_screen.008': 'Phone',
  'screens_admin_locations_screen.009': 'Type',
  'screens_admin_locations_screen.010': 'Latitude',
  'screens_admin_locations_screen.011': 'Longitude',
  'screens_admin_locations_screen.012': 'Display order',
  'screens_admin_locations_screen.013': 'Active',
  'screens_admin_locations_screen.014': 'Cancel',
  'screens_admin_locations_screen.015': 'Saving...',
  'screens_admin_locations_screen.016': 'Save',
  'screens_admin_locations_screen.017': 'Could not delete',
  'screens_admin_locations_screen.018': 'Branches & Locations',
  'screens_admin_locations_screen.019': 'Branches & locations',
  'screens_admin_locations_screen.020': 'Supported branches',
  'screens_admin_locations_screen.021': 'Add branch',
  'screens_admin_permissions_screen.001': 'Saved',
  'screens_admin_permissions_screen.002': 'Could not save',
  'screens_admin_permissions_screen.003': 'Permission Templates',
  'screens_admin_permissions_screen.004': 'Saving...',
  'screens_admin_permissions_screen.005': 'Save',
  'screens_admin_permissions_screen.006': 'Public Pages',
  'screens_admin_permissions_screen.007': 'Cards & Operations',
  'screens_admin_permissions_screen.008': 'Administration & Follow-up',
  'screens_admin_permissions_screen.009': 'View balance screen',
  'screens_admin_permissions_screen.010': 'View transactions',
  'screens_admin_permissions_screen.011': 'View cards',
  'screens_admin_permissions_screen.012': 'View quick transfer',
  'screens_admin_permissions_screen.013': 'View support',
  'screens_admin_permissions_screen.014': 'View agents and locations',
  'screens_admin_permissions_screen.015': 'View usage policy',
  'screens_admin_permissions_screen.016': 'View security settings',
  'screens_admin_permissions_screen.017': 'View account settings',
  'screens_admin_permissions_screen.018': 'Allow verification requests',
  'screens_admin_permissions_screen.019': 'Issue cards',
  'screens_admin_permissions_screen.020': 'Issue sub-shekel cards',
  'screens_admin_permissions_screen.021': 'Issue high-value cards',
  'screens_admin_permissions_screen.022': 'Issue private cards',
  'screens_admin_permissions_screen.023': 'Delete cards',
  'screens_admin_permissions_screen.024': 'Resell cards',
  'screens_admin_permissions_screen.025': 'Request card printing',
  'screens_admin_permissions_screen.026': 'Scan cards',
  'screens_admin_permissions_screen.027': 'Transfer funds',
  'screens_admin_permissions_screen.028': 'Withdraw and redeem',
  'screens_admin_permissions_screen.029': 'View customers',
  'screens_admin_permissions_screen.030': 'Lookup members',
  'screens_admin_permissions_screen.031': 'Manage users',
  'screens_admin_permissions_screen.032': 'Manage locations',
  'screens_admin_permissions_screen.033': 'Manage system settings',
  'screens_admin_permissions_screen.034': 'Review withdrawals',
  'screens_admin_permissions_screen.035': 'Review top-ups',
  'screens_admin_permissions_screen.036': 'Review devices',
  'screens_admin_permissions_screen.037': 'Review print requests',
  'screens_admin_permissions_screen.038': 'Prepare print requests',
  'screens_admin_permissions_screen.039': 'Finalize print requests',
  'screens_admin_permissions_screen.040': 'Export customer transactions',
  'screens_admin_system_settings_screen.001': 'Saved',
  'screens_admin_system_settings_screen.002': 'Could not save',
  'screens_admin_system_settings_screen.003': 'Missing data',
  'screens_admin_system_settings_screen.004': 'Could not save',
  'screens_admin_system_settings_screen.005': 'Add top-up method',
  'screens_admin_system_settings_screen.006': 'Edit top-up method',
  'screens_admin_system_settings_screen.007': 'Title',
  'screens_admin_system_settings_screen.008': 'Image URL',
  'screens_admin_system_settings_screen.009': 'Display order',
  'screens_admin_system_settings_screen.010': 'Description',
  'screens_admin_system_settings_screen.011': 'Active',
  'screens_admin_system_settings_screen.012': 'Cancel',
  'screens_admin_system_settings_screen.013': 'Saving...',
  'screens_admin_system_settings_screen.014': 'Save',
  'screens_admin_system_settings_screen.015': 'Could not delete',
  'screens_admin_system_settings_screen.016': 'System Settings',
  'screens_admin_system_settings_screen.017': 'System settings',
  'screens_admin_system_settings_screen.018': 'Contact Details',
  'screens_admin_system_settings_screen.019': 'Title',
  'screens_admin_system_settings_screen.020': 'Support WhatsApp',
  'screens_admin_system_settings_screen.021': 'Email',
  'screens_admin_system_settings_screen.022': 'Address',
  'screens_admin_system_settings_screen.023': 'Web URL',
  'screens_admin_system_settings_screen.024': 'Top-up Requests',
  'screens_admin_system_settings_screen.025': 'Add method',
  'screens_admin_system_settings_screen.026': 'Usage Policy',
  'screens_admin_system_settings_screen.027': 'Title',
  'screens_admin_system_settings_screen.028': 'Content',
  'screens_admin_system_settings_screen.029': 'Top-up fee',
  'screens_admin_system_settings_screen.030': 'Transfer fee',
  'screens_admin_system_settings_screen.031': 'Redeem fee',
  'screens_admin_system_settings_screen.032': 'Resell fee',
  'screens_admin_system_settings_screen.033': 'Print request fee',
  'screens_admin_system_settings_screen.034': 'Save settings',
  'screens_forgot_password_screen.001': 'Invalid birth date.',
  'screens_forgot_password_screen.002': 'Invalid phone number.',
  'screens_forgot_password_screen.003': 'Invalid verification code.',
  'screens_forgot_password_screen.004': 'Select birth date',
  'screens_forgot_password_screen.005': 'Cancel',
  'screens_forgot_password_screen.006': 'Confirm',
  'screens_forgot_password_screen.007': 'Error',
  'screens_forgot_password_screen.008': 'Sent successfully',
  'screens_forgot_password_screen.009': 'Error',
  'screens_forgot_password_screen.010': 'Error',
  'screens_forgot_password_screen.011': 'Account found',
  'screens_forgot_password_screen.012': 'Error',
  'screens_forgot_password_screen.013': 'Error',
  'screens_forgot_password_screen.014': 'Success',
  'screens_forgot_password_screen.015': 'Error',
  'screens_forgot_password_screen.016': 'Reset Password',
  'screens_forgot_password_screen.017': 'Reset Password',
  'screens_forgot_password_screen.018': 'Need help?',
  'screens_forgot_password_screen.019': 'National ID',
  'screens_forgot_password_screen.020': 'Birth date',
  'screens_forgot_password_screen.021': 'Select country',
  'screens_forgot_password_screen.022': 'Phone number',
  'screens_forgot_password_screen.023': 'Searching...',
  'screens_forgot_password_screen.024': 'Find account',
  'screens_forgot_password_screen.025': 'Sending...',
  'screens_forgot_password_screen.026': 'Send code',
  'screens_forgot_password_screen.027': 'Verification code',
  'screens_forgot_password_screen.028': 'Updating...',
  'screens_forgot_password_screen.029': 'Secure account recovery',
  'screens_home_screen.001': 'Cancel',
  'screens_home_screen.002': 'Shawakel',
  'screens_home_screen.003': 'Log Out',
  'screens_home_screen.004': 'All Services',
  'screens_home_screen.005': 'Choose your service.',
  'screens_home_screen.006': 'Welcome',
  'screens_home_screen.007': 'Your account is ready',
  'screens_home_screen.008': 'Quick Services',
  'screens_home_screen.009': 'Verified account',
  'screens_home_screen.010': 'Unverified account',
  'screens_home_screen.011': 'Barcode Scan',
  'screens_home_screen.012': 'Open Camera',
  'screens_inventory_screen.001': 'Digital Card Inventory',
  'screens_inventory_screen.002': 'Card Inventory',
  'screens_inventory_screen.003': 'Request card printing',
  'screens_inventory_screen.004': '{totalCards} cards',
  'screens_inventory_screen.005': 'New',
  'screens_inventory_screen.006': 'Used',
  'screens_inventory_screen.007': 'Archived',
  'screens_inventory_screen.008': 'Print',
  'screens_inventory_screen.009': 'Delete and refund',
  'screens_inventory_screen.010': 'Shawakel',
  'screens_inventory_screen.011': 'Permanent deletion?',
  'screens_inventory_screen.012': 'Cancel',
  'screens_inventory_screen.013': 'Delete',
  'screens_login_screen.001': 'Password is too long.',
  'screens_login_screen.002': 'Error',
  'screens_login_screen.003': 'Success',
  'screens_login_screen.004': 'Log In',
  'screens_login_screen.005': 'Username or phone',
  'screens_login_screen.006': 'Password',
  'screens_login_screen.007': 'Sign In',
  'screens_login_screen.008': 'Create account',
  'screens_onboarding_screen.001': 'Skip',
  'screens_onboarding_screen.002': 'Get Started',
  'screens_onboarding_screen.003': 'Next',
  'screens_otp_verification_screen.001': 'Incomplete code',
  'screens_otp_verification_screen.002': 'Completed',
  'screens_otp_verification_screen.003': 'Verification failed',
  'screens_otp_verification_screen.004': 'Code sent again',
  'screens_otp_verification_screen.005': 'Could not resend',
  'screens_otp_verification_screen.006': 'Verify Code',
  'screens_otp_verification_screen.007': 'Username',
  'screens_otp_verification_screen.008': 'WhatsApp',
  'screens_otp_verification_screen.009': 'Verification code',
  'screens_otp_verification_screen.010': 'Debug code: {debugCode}',
  'screens_otp_verification_screen.011': 'Complete registration',
  'screens_otp_verification_screen.012': 'Confirm sign in',
  'screens_otp_verification_screen.013': 'Sending...',
  'screens_otp_verification_screen.014': 'Resend',
  'screens_quick_transfer_screen.001': 'Admin',
  'screens_quick_transfer_screen.002': 'Support',
  'screens_quick_transfer_screen.003': 'User',
  'screens_quick_transfer_screen.004': 'User',
  'screens_quick_transfer_screen.005': 'Scan recipient code',
  'screens_quick_transfer_screen.006': 'Cancel',
  'screens_quick_transfer_screen.007': 'Unsupported QR code.',
  'screens_quick_transfer_screen.008': 'You cannot transfer to yourself.',
  'screens_quick_transfer_screen.009': 'User',
  'screens_quick_transfer_screen.010': 'Phone required',
  'screens_quick_transfer_screen.011': 'You cannot transfer to yourself.',
  'screens_quick_transfer_screen.012': 'Transfer complete',
  'screens_quick_transfer_screen.013': 'Transfer balance',
  'screens_quick_transfer_screen.014': 'Cancel',
  'screens_quick_transfer_screen.015': 'Confirm',
  'screens_quick_transfer_screen.016': 'Send Balance',
  'screens_quick_transfer_screen.017': 'Country code',
  'screens_quick_transfer_screen.018': 'Find recipient',
  'screens_quick_transfer_screen.019': 'Search result',
  'screens_quick_transfer_screen.020': 'Or use QR',
  'screens_quick_transfer_screen.021': 'Open camera and scan',
  'screens_quick_transfer_screen.022': 'Balance receiving code',
  'screens_register_screen.001': 'Check your data',
  'screens_register_screen.002': 'Username is required.',
  'screens_register_screen.003': 'Invalid national ID number.',
  'screens_register_screen.004': 'Please select your birth date.',
  'screens_register_screen.005': 'Invalid birth date.',
  'screens_register_screen.006': 'Password is required.',
  'screens_register_screen.007': 'Check your data',
  'screens_register_screen.008': 'Could not start registration',
  'screens_register_screen.009': 'Create a New Account',
  'screens_register_screen.010': 'Basic Information',
  'screens_register_screen.011': 'Full name',
  'screens_register_screen.012': 'Username in English',
  'screens_register_screen.013': 'National ID',
  'screens_register_screen.014': 'Birth date',
  'screens_register_screen.015': 'Contact Details',
  'screens_register_screen.016': 'Country',
  'screens_register_screen.017': 'WhatsApp number',
  'screens_register_screen.018': 'Referral phone number',
  'screens_register_screen.019': 'Account Security',
  'screens_register_screen.020': 'Password',
  'screens_register_screen.021': 'Confirm password',
  'screens_register_screen.022': 'Previous',
  'screens_register_screen.023': 'Send verification code',
  'screens_register_screen.024': 'Next',
  'screens_register_screen.025': 'Details',
  'screens_register_screen.026': 'Contact',
  'screens_register_screen.027': 'Security',
  'screens_register_screen.028': 'Admin contact',
  'screens_topup_requests_screen.001': 'Top-up Requests',
  'screens_topup_requests_screen.002': 'Top-up Requests',
  'screens_topup_requests_screen.003': '{pending} pending',
  'screens_topup_requests_screen.004': 'All',
  'screens_topup_requests_screen.005': 'Pending',
  'screens_topup_requests_screen.006': 'Approved',
  'screens_topup_requests_screen.007': 'Rejected',
  'screens_topup_requests_screen.008': 'Payment method',
  'screens_topup_requests_screen.009': 'Method number',
  'screens_topup_requests_screen.010': 'Sender name',
  'screens_topup_requests_screen.011': 'Sender phone',
  'screens_topup_requests_screen.012': 'Transfer reference',
  'screens_topup_requests_screen.013': 'Notes',
  'screens_topup_requests_screen.014': 'Approve top-up',
  'screens_topup_requests_screen.015': 'Reject',
  'screens_topup_requests_screen.016': 'Approved',
  'screens_topup_requests_screen.017': 'Rejected',
  'screens_topup_requests_screen.018': 'Under review',
  'screens_topup_requests_screen.019': 'No matching requests right now',
  'screens_topup_requests_screen.020': 'Reject top-up request',
  'screens_topup_requests_screen.021': 'Rejection reason',
  'screens_topup_requests_screen.022': 'Cancel',
  'screens_topup_requests_screen.023': 'Confirm rejection',
  'screens_topup_requests_screen.024': 'The request has been rejected.',
  'screens_transactions_screen.001': 'Could not load transaction history',
  'screens_transactions_screen.002': 'Error',
  'screens_transactions_screen.003': 'Success',
  'screens_transactions_screen.004': 'Could not export transactions',
  'screens_transactions_screen.005': 'Transactions',
  'screens_transactions_screen.006': 'Account statement',
  'screens_transactions_screen.007': 'Current balance',
  'screens_transactions_screen.008': 'Total credits',
  'screens_transactions_screen.009': 'Total debits',
  'screens_transactions_screen.010': 'Net period',
  'screens_transactions_screen.011': 'Refresh history',
  'screens_transactions_screen.012': 'Export CSV',
  'screens_transactions_screen.013': 'Search & filters',
  'screens_transactions_screen.014': 'Search transactions',
  'screens_transactions_screen.015': 'Date range',
  'screens_transactions_screen.016': 'All',
  'screens_transactions_screen.017': 'Today',
  'screens_transactions_screen.018': 'Last 7 days',
  'screens_transactions_screen.019': 'This month',
  'screens_transactions_screen.020': 'Location & type',
  'screens_transactions_screen.021': 'All',
  'screens_transactions_screen.022': 'Near branch',
  'screens_transactions_screen.023': 'Outside branches',
  'screens_transactions_screen.024': 'Printing debt',
  'screens_transactions_screen.025': 'Date range',
  'screens_transactions_screen.026': 'All',
  'screens_transactions_screen.027': 'Today',
  'screens_transactions_screen.028': 'Last 7 days',
  'screens_transactions_screen.029': 'This month',
  'screens_transactions_screen.030': 'Location & type',
  'screens_transactions_screen.031': 'All',
  'screens_transactions_screen.032': 'Near branch',
  'screens_transactions_screen.033': 'Outside branches',
  'screens_transactions_screen.034': 'Printing debt',
  'screens_transactions_screen.035': 'No transactions available',
  'screens_withdrawal_requests_screen.001': 'Withdrawal Requests',
  'screens_withdrawal_requests_screen.002': 'Track withdrawal requests',
  'screens_withdrawal_requests_screen.003': '{pending} pending',
  'screens_withdrawal_requests_screen.004': 'Search for a request...',
  'screens_withdrawal_requests_screen.005': 'All',
  'screens_withdrawal_requests_screen.006': 'Pending',
  'screens_withdrawal_requests_screen.007': 'Approved',
  'screens_withdrawal_requests_screen.008': 'Rejected',
  'screens_withdrawal_requests_screen.009': 'Transfer destination',
  'screens_withdrawal_requests_screen.010': 'Beneficiary name',
  'screens_withdrawal_requests_screen.011': 'Account number',
  'screens_withdrawal_requests_screen.012': 'Bank name',
  'screens_withdrawal_requests_screen.013': 'Notes',
  'screens_withdrawal_requests_screen.014': 'Approve',
  'screens_withdrawal_requests_screen.015': 'Reject',
  'screens_withdrawal_requests_screen.016': 'Approved',
  'screens_withdrawal_requests_screen.017': 'Rejected',
  'screens_withdrawal_requests_screen.018': 'Under review',
  'screens_withdrawal_requests_screen.019': 'No matching requests right now',
  'screens_withdrawal_requests_screen.020': 'The request has been approved.',
  'screens_withdrawal_requests_screen.021': 'Reject request',
  'screens_withdrawal_requests_screen.022': 'Rejection reason',
  'screens_withdrawal_requests_screen.023': 'Cancel',
  'screens_withdrawal_requests_screen.024': 'Confirm rejection',
  'screens_withdrawal_requests_screen.025': 'The request has been rejected.',
  'widgets_app_sidebar.001': 'Shawakel',
  'widgets_app_sidebar.002': 'Main',
  'widgets_app_sidebar.003': 'Home',
  'widgets_app_sidebar.004': 'Balance',
  'widgets_app_sidebar.005': 'Transactions',
  'widgets_app_sidebar.006': 'Cards',
  'widgets_app_sidebar.007': 'Print Requests',
  'widgets_app_sidebar.008': 'Scan Cards',
  'widgets_app_sidebar.009': 'Account',
  'widgets_app_sidebar.010': 'Account',
  'widgets_app_sidebar.011': 'Quick Transfer',
  'widgets_app_sidebar.012': 'Verify Account',
  'widgets_app_sidebar.013': 'Security',
  'widgets_app_sidebar.014': 'Admin',
  'widgets_app_sidebar.015': 'Admin Center',
  'widgets_app_sidebar.016': 'Device Requests',
  'widgets_app_sidebar.017': 'Top-up Requests',
  'widgets_app_sidebar.018': 'Branches & Locations',
  'widgets_app_sidebar.019': 'System Settings',
  'widgets_app_sidebar.020': 'More',
  'widgets_app_sidebar.021': 'Usage Policy',
  'widgets_app_sidebar.022': 'Support',
  'widgets_app_sidebar.023': 'Agents',
  'widgets_app_sidebar.024': 'Language',
  'widgets_app_sidebar.025': 'English / العربية',
  'widgets_app_sidebar.026': 'Log Out',
  'widgets_app_sidebar.027': 'Unverified',
  'widgets_app_sidebar.028': 'Verified',
  'widgets_app_sidebar.029': 'Under Review',
  'widgets_admin_admin_customer_card.001': 'Verified',
  'widgets_admin_admin_customer_card.002': 'Under review',
  'widgets_admin_admin_customer_card.003': 'Unverified',
  'widgets_admin_admin_customer_card.004': 'Balance',
  'widgets_admin_admin_customer_card.005': 'Account type',
  'widgets_admin_admin_customer_card.006': 'Verification status',
  'widgets_admin_admin_customer_card.007': 'Admin',
  'widgets_admin_admin_customer_card.008': 'System administrator',
  'widgets_admin_admin_device_request_card.001': 'Unknown device',
  'widgets_admin_admin_device_request_card.002': 'ID unavailable',
  'widgets_admin_admin_device_request_card.003': 'Access request: {createdAt}',
  'widgets_admin_admin_device_request_card.004': 'Approve',
  'widgets_admin_admin_device_request_card.005': 'Reject',
  'widgets_admin_admin_location_card.001': 'Unknown branch',
  'widgets_admin_admin_location_card.002': 'No address available',
  'widgets_admin_admin_location_card.003': 'Branch',
  'widgets_admin_admin_location_card.004': 'Active',
  'widgets_admin_admin_location_card.005': 'Disabled',
  'widgets_admin_admin_pagination_footer.001': 'Next',
  'widgets_admin_admin_pagination_footer.002': 'Previous',
  'widgets_admin_admin_settings_group.001': 'Save settings',
};
