const Map<String, String> appStringsAr = {
  'main.001': 'شواكل',
  'screens_account_settings_screen.001': 'تم الحفظ',
  'screens_account_settings_screen.002': 'تعذر الحفظ',
  'screens_account_settings_screen.003': 'بيانات ناقصة',
  'screens_account_settings_screen.004': 'عدم تطابق',
  'screens_account_settings_screen.005': 'كلمة المرور قصيرة',
  'screens_account_settings_screen.006': 'تم التحديث',
  'screens_account_settings_screen.007': 'تعذر التحديث',
  'screens_account_settings_screen.008': 'إعدادات الحساب',
  'screens_account_settings_screen.009': 'البيانات',
  'screens_account_settings_screen.010': 'كلمة المرور',
  'screens_account_settings_screen.011': 'حفظ التغييرات',
  'screens_account_settings_screen.012': 'تحديث كلمة المرور',
  'screens_account_settings_screen.013': 'كلمة المرور الحالية',
  'screens_account_settings_screen.014': 'كلمة المرور الجديدة',
  'screens_account_settings_screen.015': 'تحديث كلمة المرور',
  'screens_account_settings_screen.016': 'الحساب موثق',
  'screens_account_settings_screen.017': 'الحساب غير موثق',
  'screens_account_settings_screen.018': 'رقم غير محدد',
  'screens_account_settings_screen.019': 'البيانات الأساسية',
  'screens_account_settings_screen.020': 'الاسم الكامل',
  'screens_account_settings_screen.021': 'اسم المستخدم',
  'screens_account_settings_screen.022': 'رقم الهاتف / واتساب',
  'screens_account_settings_screen.023': 'البريد الإلكتروني',
  'screens_account_settings_screen.024': 'العنوان',
  'screens_account_settings_screen.025': 'الهوية والمعلومات الإضافية',
  'screens_account_settings_screen.026': 'رقم الهوية',
  'screens_account_settings_screen.027': 'تاريخ الميلاد',
  'screens_account_settings_screen.028': 'رقم الإحالة',
  'screens_account_settings_screen.029': 'شعار الطباعة',
  'screens_account_settings_screen.030': 'تم حفظ شعار مخصص',
  'screens_account_settings_screen.031': 'لا يوجد شعار مخصص حتى الآن',
  'screens_account_settings_screen.032': 'رفع شعار',
  'screens_account_settings_screen.033': 'حذف الشعار',
  'screens_account_settings_screen.034': 'تعذر القراءة',
  'screens_account_settings_screen.035': 'تم الرفع',
  'screens_account_settings_screen.036': 'تعذر الرفع',
  'screens_account_settings_screen.037': 'تم الحذف',
  'screens_account_settings_screen.038': 'تعذر الحذف',
  'screens_account_verification_screen.001': 'مرفقات ناقصة',
  'screens_account_verification_screen.002': 'تم الإرسال بنجاح',
  'screens_account_verification_screen.003': 'تعذر الإرسال',
  'screens_account_verification_screen.004': 'توثيق الهوية',
  'screens_account_verification_screen.005': 'توثيق الحساب',
  'screens_account_verification_screen.006': 'قيد المراجعة',
  'screens_account_verification_screen.007': 'مطلوب إعادة المحاولة',
  'screens_account_verification_screen.008': 'غير موثق بعد',
  'screens_account_verification_screen.009': 'المرفقات المطلوبة',
  'screens_account_verification_screen.010': 'صورة الهوية أو جواز السفر',
  'screens_account_verification_screen.011': 'صورة سيلفي مع الهوية',
  'screens_account_verification_screen.012': 'ملاحظات إضافية',
  'screens_account_verification_screen.013': 'إرسال طلب التوثيق',
  'screens_account_verification_screen.014': 'تم الاختيار',
  'screens_account_verification_screen.015': 'اختيار ملف',
  'screens_admin_card_print_requests_screen.001': 'طلبات طباعة البطاقات',
  'screens_admin_card_print_requests_screen.002': 'متابعة الطلبات',
  'screens_admin_card_print_requests_screen.003': 'الحالة',
  'screens_admin_card_print_requests_screen.004': 'الكل',
  'screens_admin_card_print_requests_screen.005': 'بانتظار المراجعة',
  'screens_admin_card_print_requests_screen.006': 'تمت الموافقة',
  'screens_admin_card_print_requests_screen.007': 'قيد الطباعة',
  'screens_admin_card_print_requests_screen.008': 'جاهز للتسليم',
  'screens_admin_card_print_requests_screen.009': 'مكتمل',
  'screens_admin_card_print_requests_screen.010': 'مرفوض',
  'screens_admin_card_print_requests_screen.011': 'مراجعة',
  'screens_admin_card_print_requests_screen.012': 'معتمد',
  'screens_admin_card_print_requests_screen.013': 'طباعة',
  'screens_admin_card_print_requests_screen.014': 'جاهز',
  'screens_admin_card_print_requests_screen.015': 'عميل',
  'screens_admin_card_print_requests_screen.016': 'الطلب',
  'screens_admin_card_print_requests_screen.017': 'النوع',
  'screens_admin_card_print_requests_screen.018': 'مرة واحدة',
  'screens_admin_card_print_requests_screen.019': 'عادية',
  'screens_admin_card_print_requests_screen.020': 'العدد',
  'screens_admin_card_print_requests_screen.021': 'القيمة',
  'screens_admin_card_print_requests_screen.022': 'الإجمالي',
  'screens_admin_card_print_requests_screen.023': 'موافقة',
  'screens_admin_card_print_requests_screen.024': 'رفض',
  'screens_admin_card_print_requests_screen.025': 'بدء الطباعة',
  'screens_admin_card_print_requests_screen.026': 'جاهز للتسليم',
  'screens_admin_card_print_requests_screen.027': 'إكمال الطلب',
  'screens_admin_card_print_requests_screen.028': 'جارٍ المعالجة...',
  'screens_admin_customers_screen.001': 'تعذر تحميل العملاء',
  'screens_admin_customers_screen.002': 'بيانات ناقصة',
  'screens_admin_customers_screen.003': 'تم إنشاء المستخدم',
  'screens_admin_customers_screen.004': 'تعذر الإنشاء',
  'screens_admin_customers_screen.005': 'إضافة مستخدم جديد',
  'screens_admin_customers_screen.006': 'اسم المستخدم',
  'screens_admin_customers_screen.007': 'الاسم الكامل',
  'screens_admin_customers_screen.008': 'رمز الدولة',
  'screens_admin_customers_screen.009': 'رقم الواتساب',
  'screens_admin_customers_screen.010': 'إلغاء',
  'screens_admin_customers_screen.011': 'جارٍ الحفظ...',
  'screens_admin_customers_screen.012': 'إنشاء',
  'screens_admin_customers_screen.013':
      'Ø¥Ø¹Ø§Ø¯Ø© Ø¥Ø±Ø³Ø§Ù„ Ø¨ÙŠØ§Ù†Ø§Øª ÙˆØ§ØªØ³Ø§Ø¨',
  'screens_admin_customers_screen.014': 'Ù„ØºÙŠ',
  'screens_admin_customers_screen.015': 'Ø¥Ø±Ø³Ø§Ù„',
  'screens_admin_customers_screen.016':
      'ØªÙ… Ø¥Ø¹Ø§Ø¯Ø© Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø¨ÙŠØ§Ù†Ø§Øª.',
  'screens_admin_customers_screen.017': 'إدارة العملاء',
  'screens_admin_customers_screen.018': 'إدارة العملاء',
  'screens_admin_customers_screen.019': 'إجمالي الظاهر',
  'screens_admin_customers_screen.020': 'إجمالي النظام',
  'screens_admin_customers_screen.021': 'العملاء',
  'screens_admin_customers_screen.022': 'إضافة مستخدم',
  'screens_admin_customers_screen.023': 'ابحث عن عميل...',
  'screens_admin_customer_screen.001': 'إعادة إرسال بيانات المستخدم',
  'screens_admin_customer_screen.002': 'إلغاء',
  'screens_admin_customer_screen.003': 'تأكيد الإرسال',
  'screens_admin_customer_screen.004': 'تم الإرسال',
  'screens_admin_customer_screen.005': 'تعذر الإرسال',
  'screens_admin_customer_screen.006': 'عميل شواكل',
  'screens_admin_customer_screen.007': 'نظرة عامة',
  'screens_admin_customer_screen.008': 'سجل الحركات',
  'screens_admin_customer_screen.009': 'الإدارة والرسوم',
  'screens_admin_customer_screen.010': 'الصلاحيات',
  'screens_admin_customer_screen.011': 'الأجهزة',
  'screens_admin_customer_screen.012': 'إجراءات سريعة',
  'screens_admin_customer_screen.013': 'الرصيد الحالي',
  'screens_admin_customer_screen.014': 'حالة الحساب',
  'screens_admin_customer_screen.015': 'معطل',
  'screens_admin_customer_screen.016': 'نشط',
  'screens_admin_customer_screen.017': 'بيانات التواصل',
  'screens_admin_customer_screen.018': 'اسم المستخدم',
  'screens_admin_customer_screen.019': 'الاسم الرباعي',
  'screens_admin_customer_screen.020': 'الواتساب',
  'screens_admin_customer_screen.021': 'تاريخ الانضمام',
  'screens_admin_customer_screen.022': 'عميل أساسي',
  'screens_admin_customer_screen.023': 'سجل حركات العميل',
  'screens_admin_customer_screen.024': 'الكل',
  'screens_admin_customer_screen.025': 'قرب الفروع',
  'screens_admin_customer_screen.026': 'خارج الفروع',
  'screens_admin_customer_screen.027': 'لا توجد حركات حديثة.',
  'screens_admin_customer_screen.028': 'إدارة الحساب والرسوم',
  'screens_admin_customer_screen.029': 'حالة التوثيق',
  'screens_admin_customer_screen.030': 'عضوية مقيدة',
  'screens_admin_customer_screen.031': 'عضوية موثقة',
  'screens_admin_customer_screen.032': 'عضوية مطورة',
  'screens_admin_customer_screen.033': 'غير موثق',
  'screens_admin_customer_screen.034': 'قيد المراجعة',
  'screens_admin_customer_screen.035': 'موثق / مفعل',
  'screens_admin_customer_screen.036': 'مرفوض',
  'screens_admin_customer_screen.037': 'دور الحساب',
  'screens_admin_customer_screen.038': 'مستخدم عادي',
  'screens_admin_customer_screen.039': 'فريق الدعم',
  'screens_admin_customer_screen.040': 'مدير فني',
  'screens_admin_customer_screen.041': 'سقف دين الطباعة (₪)',
  'screens_admin_customer_screen.042': 'رسوم مخصصة لهذا العميل (%)',
  'screens_admin_customer_screen.043': 'حفظ التغييرات',
  'screens_admin_customer_screen.044': 'الإيداع',
  'screens_admin_customer_screen.045': 'السحب',
  'screens_admin_customer_screen.046': 'التحويل',
  'screens_admin_customer_screen.047': 'الاسترداد',
  'screens_admin_customer_screen.048': 'إعادة البيع',
  'screens_admin_customer_screen.049': 'طلب الطباعة',
  'screens_admin_customer_screen.050': 'صلاحيات البطاقات والإدارة',
  'screens_admin_customer_screen.051': 'إصدار بطاقات رصيد',
  'screens_admin_customer_screen.052': 'طلب طباعة البطاقات',
  'screens_admin_customer_screen.053': 'إصدار أجزاء الشيكل',
  'screens_admin_customer_screen.054': 'إصدار بطاقات عالية القيمة',
  'screens_admin_customer_screen.055': 'إعادة تفعيل البطاقات المستخدمة',
  'screens_admin_customer_screen.056': 'مراجعة طلبات طباعة البطاقات',
  'screens_admin_customer_screen.057': 'تجهيز وطباعة الطلبات',
  'screens_admin_customer_screen.058': 'إكمال وتسليم الطلبات',
  'screens_admin_customer_screen.059': 'إدارة المستخدمين الآخرين',
  'screens_admin_customer_screen.060': 'سياسة الأجهزة ونقاط الوصول',
  'screens_admin_customer_screen.061': 'الحد الأقصى للأجهزة المسموح بها',
  'screens_admin_customer_screen.062': 'تحديث سياسة الأجهزة',
  'screens_admin_customer_screen.063': 'الأجهزة النشطة',
  'screens_admin_customer_screen.064': 'جهاز غير معروف',
  'screens_admin_dashboard_screen.001': 'مركز الإدارة',
  'screens_admin_dashboard_screen.002': 'مركز الإدارة السريع',
  'screens_admin_device_requests_screen.001': 'طلبات الأجهزة',
  'screens_admin_device_requests_screen.002': 'طلبات الأجهزة',
  'screens_admin_device_requests_screen.003': 'الطلبات المعلقة',
  'screens_admin_locations_screen.001': 'تعذر تحميل الفروع',
  'screens_admin_locations_screen.002': 'بيانات ناقصة',
  'screens_admin_locations_screen.003': 'تعذر الحفظ',
  'screens_admin_locations_screen.004': 'إضافة فرع',
  'screens_admin_locations_screen.005': 'تعديل الفرع',
  'screens_admin_locations_screen.006': 'اسم الفرع',
  'screens_admin_locations_screen.007': 'العنوان',
  'screens_admin_locations_screen.008': 'الهاتف',
  'screens_admin_locations_screen.009': 'النوع',
  'screens_admin_locations_screen.010': 'خط العرض',
  'screens_admin_locations_screen.011': 'خط الطول',
  'screens_admin_locations_screen.012': 'ترتيب الظهور',
  'screens_admin_locations_screen.013': 'مفعل',
  'screens_admin_locations_screen.014': 'إلغاء',
  'screens_admin_locations_screen.015': 'جارٍ الحفظ...',
  'screens_admin_locations_screen.016': 'حفظ',
  'screens_admin_locations_screen.017': 'تعذر الحذف',
  'screens_admin_locations_screen.018': 'الفروع والمواقع',
  'screens_admin_locations_screen.019': 'الفروع والمواقع',
  'screens_admin_locations_screen.020': 'الفروع المدعومة',
  'screens_admin_locations_screen.021': 'إضافة فرع',
  'screens_admin_permissions_screen.001': 'تم الحفظ',
  'screens_admin_permissions_screen.002': 'تعذر الحفظ',
  'screens_admin_permissions_screen.003': 'قوالب الصلاحيات',
  'screens_admin_permissions_screen.004': 'جارٍ الحفظ...',
  'screens_admin_permissions_screen.005': 'حفظ',
  'screens_admin_permissions_screen.006': 'الصفحات العامة',
  'screens_admin_permissions_screen.007': 'البطاقات والعمليات',
  'screens_admin_permissions_screen.008': 'الإدارة والمتابعة',
  'screens_admin_permissions_screen.009': 'عرض صفحة الرصيد',
  'screens_admin_permissions_screen.010': 'عرض الحركات',
  'screens_admin_permissions_screen.011': 'عرض البطاقات',
  'screens_admin_permissions_screen.012': 'عرض النقل السريع',
  'screens_admin_permissions_screen.013': 'عرض الدعم',
  'screens_admin_permissions_screen.014': 'عرض الوكلاء والمواقع',
  'screens_admin_permissions_screen.015': 'عرض سياسة الاستخدام',
  'screens_admin_permissions_screen.016': 'عرض الأمان',
  'screens_admin_permissions_screen.017': 'عرض الحساب',
  'screens_admin_permissions_screen.018': 'السماح بطلب التوثيق',
  'screens_admin_permissions_screen.019': 'إصدار البطاقات',
  'screens_admin_permissions_screen.020': 'بطاقات أقل من شيكل',
  'screens_admin_permissions_screen.021': 'بطاقات عالية القيمة',
  'screens_admin_permissions_screen.022': 'بطاقات خاصة',
  'screens_admin_permissions_screen.023': 'حذف البطاقات',
  'screens_admin_permissions_screen.024': 'إعادة بيع البطاقات',
  'screens_admin_permissions_screen.025': 'طلب طباعة البطاقات',
  'screens_admin_permissions_screen.026': 'فحص البطاقات',
  'screens_admin_permissions_screen.027': 'التحويل',
  'screens_admin_permissions_screen.028': 'السحب والاسترداد',
  'screens_admin_permissions_screen.029': 'عرض العملاء',
  'screens_admin_permissions_screen.030': 'البحث عن الأعضاء',
  'screens_admin_permissions_screen.031': 'إدارة المستخدمين',
  'screens_admin_permissions_screen.032': 'إدارة المواقع',
  'screens_admin_permissions_screen.033': 'إدارة إعدادات النظام',
  'screens_admin_permissions_screen.034': 'مراجعة السحب',
  'screens_admin_permissions_screen.035': 'مراجعة شحن الرصيد',
  'screens_admin_permissions_screen.036': 'مراجعة الأجهزة',
  'screens_admin_permissions_screen.037': 'مراجعة طلبات الطباعة',
  'screens_admin_permissions_screen.038': 'تجهيز طلبات الطباعة',
  'screens_admin_permissions_screen.039': 'إكمال طلبات الطباعة',
  'screens_admin_permissions_screen.040': 'تصدير كشف العملاء',
  'screens_admin_system_settings_screen.001': 'تم الحفظ',
  'screens_admin_system_settings_screen.002': 'تعذر الحفظ',
  'screens_admin_system_settings_screen.003': 'بيانات ناقصة',
  'screens_admin_system_settings_screen.004': 'تعذر الحفظ',
  'screens_admin_system_settings_screen.005': 'إضافة طريقة شحن',
  'screens_admin_system_settings_screen.006': 'تعديل طريقة شحن',
  'screens_admin_system_settings_screen.007': 'العنوان',
  'screens_admin_system_settings_screen.008': 'رابط الصورة',
  'screens_admin_system_settings_screen.009': 'ترتيب الظهور',
  'screens_admin_system_settings_screen.010': 'الوصف',
  'screens_admin_system_settings_screen.011': 'مفعل',
  'screens_admin_system_settings_screen.012': 'إلغاء',
  'screens_admin_system_settings_screen.013': 'جارٍ الحفظ...',
  'screens_admin_system_settings_screen.014': 'حفظ',
  'screens_admin_system_settings_screen.015': 'تعذر الحذف',
  'screens_admin_system_settings_screen.016': 'إعدادات النظام',
  'screens_admin_system_settings_screen.017': 'إعدادات النظام',
  'screens_admin_system_settings_screen.018': 'بيانات التواصل',
  'screens_admin_system_settings_screen.019': 'العنوان',
  'screens_admin_system_settings_screen.020': 'واتساب الدعم',
  'screens_admin_system_settings_screen.021': 'البريد',
  'screens_admin_system_settings_screen.022': 'العنوان الفعلي',
  'screens_admin_system_settings_screen.023': 'رابط الويب',
  'screens_admin_system_settings_screen.024': 'طلبات شحن الرصيد',
  'screens_admin_system_settings_screen.025': 'إضافة طريقة',
  'screens_admin_system_settings_screen.026': 'سياسة الاستخدام',
  'screens_admin_system_settings_screen.027': 'العنوان',
  'screens_admin_system_settings_screen.028': 'المحتوى',
  'screens_admin_system_settings_screen.029': 'رسوم الإيداع',
  'screens_admin_system_settings_screen.030': 'رسوم التحويل',
  'screens_admin_system_settings_screen.031': 'رسوم الاسترداد',
  'screens_admin_system_settings_screen.032': 'رسوم إعادة البيع',
  'screens_admin_system_settings_screen.033': 'رسوم طلب الطباعة',
  'screens_admin_system_settings_screen.034': 'حفظ الإعدادات',
  'screens_forgot_password_screen.001': 'تاريخ الميلاد غير صالح.',
  'screens_forgot_password_screen.002': 'رقم الجوال غير صالح.',
  'screens_forgot_password_screen.003': 'رمز التحقق غير صالح.',
  'screens_forgot_password_screen.004': 'اختر تاريخ الميلاد',
  'screens_forgot_password_screen.005': 'إلغاء',
  'screens_forgot_password_screen.006': 'اعتماد',
  'screens_forgot_password_screen.007': 'خطأ',
  'screens_forgot_password_screen.008': 'تم الإرسال',
  'screens_forgot_password_screen.009': 'خطأ',
  'screens_forgot_password_screen.010': 'خطأ',
  'screens_forgot_password_screen.011': 'تم العثور على الحساب',
  'screens_forgot_password_screen.012': 'خطأ',
  'screens_forgot_password_screen.013': 'خطأ',
  'screens_forgot_password_screen.014': 'نجاح',
  'screens_forgot_password_screen.015': 'خطأ',
  'screens_forgot_password_screen.016': 'استعادة كلمة المرور',
  'screens_forgot_password_screen.017': 'استعادة كلمة المرور',
  'screens_forgot_password_screen.018': 'تحتاج مساعدة؟',
  'screens_forgot_password_screen.019': 'رقم الهوية',
  'screens_forgot_password_screen.020': 'تاريخ الميلاد',
  'screens_forgot_password_screen.021': 'اختر الدولة',
  'screens_forgot_password_screen.022': 'رقم الجوال',
  'screens_forgot_password_screen.023': 'جارٍ البحث...',
  'screens_forgot_password_screen.024': 'بحث عن الحساب',
  'screens_forgot_password_screen.025': 'جارٍ الإرسال...',
  'screens_forgot_password_screen.026': 'إرسال الرمز',
  'screens_forgot_password_screen.027': 'رمز التحقق',
  'screens_forgot_password_screen.028': 'جارٍ التحديث...',
  'screens_forgot_password_screen.029': 'استعادة الحساب بشكل آمن',
  'screens_home_screen.001': 'إلغاء',
  'screens_home_screen.002': 'شواكل',
  'screens_home_screen.003': 'تسجيل الخروج',
  'screens_home_screen.004': 'جميع الخدمات',
  'screens_home_screen.005': 'اختر خدمتك.',
  'screens_home_screen.006': 'مرحبًا بك',
  'screens_home_screen.007': 'حسابك جاهز',
  'screens_home_screen.008': 'الخدمات السريعة',
  'screens_home_screen.009': 'الحساب موثق',
  'screens_home_screen.010': 'الحساب غير موثق',
  'screens_home_screen.011': 'فحص الباركود',
  'screens_home_screen.012': 'فتح الكاميرا',
  'screens_inventory_screen.001': 'مخزون البطاقات الرقمية',
  'screens_inventory_screen.002': 'مخزون البطاقات',
  'screens_inventory_screen.003': 'طلب طباعة بطاقات',
  'screens_inventory_screen.004': '{totalCards} بطاقة',
  'screens_inventory_screen.005': 'جديدة',
  'screens_inventory_screen.006': 'مستخدمة',
  'screens_inventory_screen.007': 'مؤرشفة',
  'screens_inventory_screen.008': 'طباعة',
  'screens_inventory_screen.009': 'حذف وإرجاع القيمة',
  'screens_inventory_screen.010': 'شواكل',
  'screens_inventory_screen.011': 'حذف نهائي؟',
  'screens_inventory_screen.012': 'إلغاء',
  'screens_inventory_screen.013': 'حذف',
  'screens_login_screen.001': 'كلمة المرور طويلة جدًا.',
  'screens_login_screen.002': 'خطأ',
  'screens_login_screen.003': 'نجاح',
  'screens_login_screen.004': 'تسجيل الدخول',
  'screens_login_screen.005': 'اسم المستخدم أو الجوال',
  'screens_login_screen.006': 'كلمة المرور',
  'screens_login_screen.007': 'دخول',
  'screens_login_screen.008': 'إنشاء حساب جديد',
  'screens_onboarding_screen.001': 'تخطي',
  'screens_onboarding_screen.002': 'ابدأ الآن',
  'screens_onboarding_screen.003': 'التالي',
  'screens_otp_verification_screen.001': 'رمز غير مكتمل',
  'screens_otp_verification_screen.002': 'تم التفعيل',
  'screens_otp_verification_screen.003': 'تعذر التحقق',
  'screens_otp_verification_screen.004': 'تمت إعادة الإرسال',
  'screens_otp_verification_screen.005': 'تعذر الإرسال',
  'screens_otp_verification_screen.006': 'تأكيد الرمز',
  'screens_otp_verification_screen.007': 'اسم المستخدم',
  'screens_otp_verification_screen.008': 'واتساب',
  'screens_otp_verification_screen.009': 'رمز التحقق',
  'screens_otp_verification_screen.010': 'رمز تجريبي: {debugCode}',
  'screens_otp_verification_screen.011': 'إكمال إنشاء الحساب',
  'screens_otp_verification_screen.012': 'تأكيد الدخول',
  'screens_otp_verification_screen.013': 'جارٍ الإرسال...',
  'screens_otp_verification_screen.014': 'إعادة الإرسال',
  'screens_quick_transfer_screen.001': 'إدارة',
  'screens_quick_transfer_screen.002': 'دعم',
  'screens_quick_transfer_screen.003': 'مستخدم',
  'screens_quick_transfer_screen.004': 'مستخدم',
  'screens_quick_transfer_screen.005': 'امسح رمز المستلم',
  'screens_quick_transfer_screen.006': 'إلغاء',
  'screens_quick_transfer_screen.007': 'الرمز غير مدعوم.',
  'screens_quick_transfer_screen.008': 'لا يمكن التحويل لنفسك.',
  'screens_quick_transfer_screen.009': 'مستخدم',
  'screens_quick_transfer_screen.010': 'رقم مطلوب',
  'screens_quick_transfer_screen.011': 'لا يمكن التحويل لنفسك.',
  'screens_quick_transfer_screen.012': 'تم التحويل',
  'screens_quick_transfer_screen.013': 'تحويل رصيد',
  'screens_quick_transfer_screen.014': 'إلغاء',
  'screens_quick_transfer_screen.015': 'تأكيد',
  'screens_quick_transfer_screen.016': 'إرسال الرصيد',
  'screens_quick_transfer_screen.017': 'رمز الدولة',
  'screens_quick_transfer_screen.018': 'بحث عن المستلم',
  'screens_quick_transfer_screen.019': 'نتيجة البحث',
  'screens_quick_transfer_screen.020': 'أو استخدم QR',
  'screens_quick_transfer_screen.021': 'فتح الكاميرا والمسح',
  'screens_quick_transfer_screen.022': 'رمز استلام الرصيد',
  'screens_register_screen.001': 'تحقق من البيانات',
  'screens_register_screen.002': 'اسم المستخدم مطلوب.',
  'screens_register_screen.003': 'رقم الهوية غير صالح.',
  'screens_register_screen.004': 'اختر تاريخ الميلاد.',
  'screens_register_screen.005': 'تاريخ الميلاد غير صالح.',
  'screens_register_screen.006': 'كلمة المرور مطلوبة.',
  'screens_register_screen.007': 'تحقق من البيانات',
  'screens_register_screen.008': 'تعذر بدء التسجيل',
  'screens_register_screen.009': 'إنشاء حساب جديد',
  'screens_register_screen.010': 'البيانات الأساسية',
  'screens_register_screen.011': 'الاسم الكامل',
  'screens_register_screen.012': 'اسم المستخدم بالإنجليزية',
  'screens_register_screen.013': 'رقم الهوية',
  'screens_register_screen.014': 'تاريخ الميلاد',
  'screens_register_screen.015': 'بيانات التواصل',
  'screens_register_screen.016': 'الدولة',
  'screens_register_screen.017': 'رقم الواتساب',
  'screens_register_screen.018': 'رقم المحيل أو الموصي',
  'screens_register_screen.019': 'تأمين الحساب',
  'screens_register_screen.020': 'كلمة المرور',
  'screens_register_screen.021': 'تأكيد كلمة المرور',
  'screens_register_screen.022': 'السابق',
  'screens_register_screen.023': 'إرسال رمز التحقق',
  'screens_register_screen.024': 'التالي',
  'screens_register_screen.025': 'البيانات',
  'screens_register_screen.026': 'التواصل',
  'screens_register_screen.027': 'الحماية',
  'screens_register_screen.028': 'رقم الإدارة',
  'screens_topup_requests_screen.001': 'طلبات شحن الرصيد',
  'screens_topup_requests_screen.002': 'طلبات شحن الرصيد',
  'screens_topup_requests_screen.003': '{pending} طلب معلق',
  'screens_topup_requests_screen.004': 'الكل',
  'screens_topup_requests_screen.005': 'المعلقة',
  'screens_topup_requests_screen.006': 'المعتمدة',
  'screens_topup_requests_screen.007': 'المرفوضة',
  'screens_topup_requests_screen.008': 'طريقة الدفع',
  'screens_topup_requests_screen.009': 'رقم الطريقة',
  'screens_topup_requests_screen.010': 'اسم المحول',
  'screens_topup_requests_screen.011': 'جوال المحول',
  'screens_topup_requests_screen.012': 'مرجع التحويل',
  'screens_topup_requests_screen.013': 'الملاحظات',
  'screens_topup_requests_screen.014': 'اعتماد الشحن',
  'screens_topup_requests_screen.015': 'رفض',
  'screens_topup_requests_screen.016': 'تم الاعتماد',
  'screens_topup_requests_screen.017': 'مرفوض',
  'screens_topup_requests_screen.018': 'قيد المراجعة',
  'screens_topup_requests_screen.019': 'لا توجد طلبات مطابقة حاليًا',
  'screens_topup_requests_screen.020': 'رفض طلب الشحن',
  'screens_topup_requests_screen.021': 'سبب الرفض',
  'screens_topup_requests_screen.022': 'إلغاء',
  'screens_topup_requests_screen.023': 'تأكيد الرفض',
  'screens_topup_requests_screen.024': 'تم رفض الطلب.',
  'screens_transactions_screen.001': 'تعذر تحميل سجل الحركات',
  'screens_transactions_screen.002': 'خطأ',
  'screens_transactions_screen.003': 'نجاح',
  'screens_transactions_screen.004': 'تعذر تصدير الحركات',
  'screens_transactions_screen.005': 'سجل الحركات',
  'screens_transactions_screen.006': 'كشف الحساب',
  'screens_transactions_screen.007': 'الرصيد الحالي',
  'screens_transactions_screen.008': 'إجمالي الإضافات',
  'screens_transactions_screen.009': 'إجمالي الخصومات',
  'screens_transactions_screen.010': 'صافي الفترة',
  'screens_transactions_screen.011': 'تحديث السجل',
  'screens_transactions_screen.012': 'تصدير CSV',
  'screens_transactions_screen.013': 'البحث والفلاتر',
  'screens_transactions_screen.014': 'البحث في الحركات',
  'screens_transactions_screen.015': 'الفترة الزمنية',
  'screens_transactions_screen.016': 'الكل',
  'screens_transactions_screen.017': 'اليوم',
  'screens_transactions_screen.018': 'آخر 7 أيام',
  'screens_transactions_screen.019': 'هذا الشهر',
  'screens_transactions_screen.020': 'الموقع والنوع',
  'screens_transactions_screen.021': 'الكل',
  'screens_transactions_screen.022': 'قرب فرع',
  'screens_transactions_screen.023': 'خارج الفروع',
  'screens_transactions_screen.024': 'دين الطباعة',
  'screens_transactions_screen.025': 'الفترة الزمنية',
  'screens_transactions_screen.026': 'الكل',
  'screens_transactions_screen.027': 'اليوم',
  'screens_transactions_screen.028': 'آخر 7 أيام',
  'screens_transactions_screen.029': 'هذا الشهر',
  'screens_transactions_screen.030': 'الموقع والنوع',
  'screens_transactions_screen.031': 'الكل',
  'screens_transactions_screen.032': 'قرب فرع',
  'screens_transactions_screen.033': 'خارج الفروع',
  'screens_transactions_screen.034': 'دين الطباعة',
  'screens_transactions_screen.035': 'لا توجد حركات متاحة',
  'screens_withdrawal_requests_screen.001': 'طلبات السحب',
  'screens_withdrawal_requests_screen.002': 'متابعة طلبات السحب',
  'screens_withdrawal_requests_screen.003': '{pending} طلب معلق',
  'screens_withdrawal_requests_screen.004': 'ابحث عن طلب...',
  'screens_withdrawal_requests_screen.005': 'الكل',
  'screens_withdrawal_requests_screen.006': 'المعلقة',
  'screens_withdrawal_requests_screen.007': 'المكتملة',
  'screens_withdrawal_requests_screen.008': 'المرفوضة',
  'screens_withdrawal_requests_screen.009': 'جهة التحويل',
  'screens_withdrawal_requests_screen.010': 'اسم المستفيد',
  'screens_withdrawal_requests_screen.011': 'رقم الحساب',
  'screens_withdrawal_requests_screen.012': 'اسم البنك',
  'screens_withdrawal_requests_screen.013': 'الملاحظات',
  'screens_withdrawal_requests_screen.014': 'اعتماد',
  'screens_withdrawal_requests_screen.015': 'رفض',
  'screens_withdrawal_requests_screen.016': 'تم الاعتماد',
  'screens_withdrawal_requests_screen.017': 'مرفوض',
  'screens_withdrawal_requests_screen.018': 'قيد المراجعة',
  'screens_withdrawal_requests_screen.019': 'لا توجد طلبات مطابقة حاليًا',
  'screens_withdrawal_requests_screen.020': 'تم اعتماد الطلب.',
  'screens_withdrawal_requests_screen.021': 'رفض الطلب',
  'screens_withdrawal_requests_screen.022': 'سبب الرفض',
  'screens_withdrawal_requests_screen.023': 'إلغاء',
  'screens_withdrawal_requests_screen.024': 'تأكيد الرفض',
  'screens_withdrawal_requests_screen.025': 'تم رفض الطلب.',
  'widgets_app_sidebar.001': 'شواكل',
  'widgets_app_sidebar.002': 'الرئيسية',
  'widgets_app_sidebar.003': 'الرئيسية',
  'widgets_app_sidebar.004': 'الرصيد',
  'widgets_app_sidebar.005': 'الحركات',
  'widgets_app_sidebar.006': 'البطاقات',
  'widgets_app_sidebar.007': 'طلبات الطباعة',
  'widgets_app_sidebar.008': 'فحص البطاقات',
  'widgets_app_sidebar.009': 'الحساب',
  'widgets_app_sidebar.010': 'الحساب',
  'widgets_app_sidebar.011': 'النقل السريع',
  'widgets_app_sidebar.012': 'توثيق الحساب',
  'widgets_app_sidebar.013': 'الأمان',
  'widgets_app_sidebar.014': 'الإدارة',
  'widgets_app_sidebar.015': 'مركز الإدارة',
  'widgets_app_sidebar.016': 'طلبات الأجهزة',
  'widgets_app_sidebar.017': 'طلبات شحن الرصيد',
  'widgets_app_sidebar.018': 'الفروع والمواقع',
  'widgets_app_sidebar.019': 'إعدادات النظام',
  'widgets_app_sidebar.020': 'المزيد',
  'widgets_app_sidebar.021': 'سياسة الاستخدام',
  'widgets_app_sidebar.022': 'الدعم',
  'widgets_app_sidebar.023': 'الوكلاء',
  'widgets_app_sidebar.024': 'اللغة',
  'widgets_app_sidebar.025': 'العربية / English',
  'widgets_app_sidebar.026': 'تسجيل الخروج',
  'widgets_app_sidebar.027': 'غير موثق',
  'widgets_app_sidebar.028': 'موثق',
  'widgets_app_sidebar.029': 'قيد المراجعة',
  'widgets_admin_admin_customer_card.001': 'موثق',
  'widgets_admin_admin_customer_card.002': 'قيد المراجعة',
  'widgets_admin_admin_customer_card.003': 'غير موثق',
  'widgets_admin_admin_customer_card.004': 'الرصيد',
  'widgets_admin_admin_customer_card.005': 'نوع الحساب',
  'widgets_admin_admin_customer_card.006': 'حالة التوثيق',
  'widgets_admin_admin_customer_card.007': 'مسؤول',
  'widgets_admin_admin_customer_card.008': 'مسؤول نظام',
  'widgets_admin_admin_device_request_card.001': 'جهاز غير معروف',
  'widgets_admin_admin_device_request_card.002': 'ID غير متوفر',
  'widgets_admin_admin_device_request_card.003': 'طلب الوصول: {createdAt}',
  'widgets_admin_admin_device_request_card.004': 'قبول',
  'widgets_admin_admin_device_request_card.005': 'رفض',
  'widgets_admin_admin_location_card.001': 'فرع غير معروف',
  'widgets_admin_admin_location_card.002': 'لا يوجد عنوان',
  'widgets_admin_admin_location_card.003': 'فرع',
  'widgets_admin_admin_location_card.004': 'مفعل',
  'widgets_admin_admin_location_card.005': 'معطل',
  'widgets_admin_admin_pagination_footer.001': 'التالي',
  'widgets_admin_admin_pagination_footer.002': 'السابق',
  'widgets_admin_admin_settings_group.001': 'حفظ الإعدادات',
};
