const Map<String, String> appStringsEn = {
  'main.001': 'shwakil',
  'screens_account_settings_screen.001': 'Saved',
  'screens_account_settings_screen.002': 'Could not save',
  'screens_account_settings_screen.003': 'Missing data',
  'screens_account_settings_screen.004': 'Mismatch',
  'screens_account_settings_screen.005': 'Password too short',
  'screens_account_settings_screen.006': 'Updated',
  'screens_account_settings_screen.007': 'Could not update',
  'screens_account_settings_screen.008': 'Account Settings',
  'screens_account_settings_screen.009': 'Profile',
  'screens_account_settings_screen.010': 'Password',
  'screens_account_settings_screen.011': 'Save changes',
  'screens_account_settings_screen.012': 'Update password',
  'screens_account_settings_screen.013': 'Current password',
  'screens_account_settings_screen.014': 'New password',
  'screens_account_settings_screen.015': 'Update password',
  'screens_account_settings_screen.016': 'Verified account',
  'screens_account_settings_screen.017': 'Unverified account',
  'screens_account_settings_screen.018': 'No phone number',
  'screens_account_settings_screen.019': 'Basic information',
  'screens_account_settings_screen.020': 'Full name',
  'screens_account_settings_screen.021': 'Username',
  'screens_account_settings_screen.022': 'Phone / WhatsApp',
  'screens_account_settings_screen.023': 'Email',
  'screens_account_settings_screen.024': 'Address',
  'screens_account_settings_screen.025': 'Identity & extra details',
  'screens_account_settings_screen.026': 'National ID',
  'screens_account_settings_screen.027': 'Birth date',
  'screens_account_settings_screen.028': 'Referral number',
  'screens_account_settings_screen.029': 'Print logo',
  'screens_account_settings_screen.030': 'A custom logo is saved',
  'screens_account_settings_screen.031': 'No custom logo yet',
  'screens_account_settings_screen.032': 'Upload logo',
  'screens_account_settings_screen.033': 'Delete logo',
  'screens_account_settings_screen.034': 'Could not read file',
  'screens_account_settings_screen.035': 'Uploaded',
  'screens_account_settings_screen.036': 'Could not upload',
  'screens_account_settings_screen.037': 'Deleted',
  'screens_account_settings_screen.038': 'Could not delete',
  'screens_account_settings_screen.039':
      'Profile details were updated successfully.',
  'screens_account_settings_screen.040':
      'Enter the current password, new password, and confirmation.',
  'screens_account_settings_screen.041':
      'The new password confirmation does not match.',
  'screens_account_settings_screen.042':
      'The new password must be at least 8 characters.',
  'screens_account_settings_screen.043': 'Password changed successfully.',
  'screens_account_settings_screen.044':
      'Enter the current password, then the new one.',
  'screens_account_settings_screen.045': 'Confirm new password',
  'screens_account_settings_screen.046': '{count} fields need completion',
  'screens_account_settings_screen.047':
      'Some fields are locked after verification. Contact support to edit them.',
  'screens_account_settings_screen.048':
      'You can complete only the missing fields. After saving, they will be locked automatically because the account is verified.',
  'screens_account_settings_screen.049':
      'A logo shown on cards during printing.',
  'screens_account_settings_screen.050': 'The logo file could not be read.',
  'screens_account_settings_screen.051':
      'The print logo was updated successfully.',
  'screens_account_settings_screen.052':
      'The print logo was deleted successfully.',
  'screens_account_verification_screen.001': 'Missing attachments',
  'screens_account_verification_screen.002': 'Submitted successfully',
  'screens_account_verification_screen.003': 'Submission failed',
  'screens_account_verification_screen.004': 'Identity Verification',
  'screens_account_verification_screen.005': 'Verify your account',
  'screens_account_verification_screen.006': 'Under review',
  'screens_account_verification_screen.007': 'Resubmission required',
  'screens_account_verification_screen.008': 'Not verified yet',
  'screens_account_verification_screen.009': 'Required documents',
  'screens_account_verification_screen.010': 'Identity or passport image',
  'screens_account_verification_screen.011': 'Selfie with identity',
  'screens_account_verification_screen.012': 'Additional notes',
  'screens_account_verification_screen.013': 'Submit verification request',
  'screens_account_verification_screen.014': 'Selected',
  'screens_account_verification_screen.015': 'Choose file',
  'screens_account_verification_screen.016':
      'Please add the required images, national ID, and birth date before submitting.',
  'screens_account_verification_screen.017':
      'Your verification request is now under review.',
  'screens_account_verification_screen.018':
      'Upload clear documents to unlock full transfers and advanced account features.',
  'screens_account_verification_screen.019':
      'Your request is under review by the administration. You will be notified when the status changes.',
  'screens_account_verification_screen.020':
      'Your previous request was rejected. Please upload clearer identity and selfie images.',
  'screens_account_verification_screen.021':
      'Your account is not verified yet. Upload the required documents to complete activation.',
  'screens_account_verification_screen.022':
      'Upload a clear identity image and a selfie holding the same identity document to speed up review.',
  'screens_account_verification_screen.023':
      'Please review your details and upload clearer files before resubmitting.',
  'screens_account_verification_screen.024': 'National ID',
  'screens_account_verification_screen.025': 'Birth date',
  'screens_account_verification_screen.026': 'Please enter a valid birth date.',
  'screens_admin_card_print_requests_screen.001': 'Card Print Requests',
  'screens_admin_card_print_requests_screen.002': 'Request tracking',
  'screens_admin_card_print_requests_screen.003': 'Status',
  'screens_admin_card_print_requests_screen.004': 'All',
  'screens_admin_card_print_requests_screen.005': 'Pending review',
  'screens_admin_card_print_requests_screen.006': 'Approved',
  'screens_admin_card_print_requests_screen.007': 'Printing',
  'screens_admin_card_print_requests_screen.008': 'Ready',
  'screens_admin_card_print_requests_screen.009': 'Completed',
  'screens_admin_card_print_requests_screen.010': 'Rejected',
  'screens_admin_card_print_requests_screen.011': 'Review',
  'screens_admin_card_print_requests_screen.012': 'Approved',
  'screens_admin_card_print_requests_screen.013': 'Printing',
  'screens_admin_card_print_requests_screen.014': 'Ready',
  'screens_admin_card_print_requests_screen.015': 'Customer',
  'screens_admin_card_print_requests_screen.016': 'Request',
  'screens_admin_card_print_requests_screen.017': 'Type',
  'screens_admin_card_print_requests_screen.018': 'Single use',
  'screens_admin_card_print_requests_screen.019': 'Regular',
  'screens_admin_card_print_requests_screen.020': 'Quantity',
  'screens_admin_card_print_requests_screen.021': 'Value',
  'screens_admin_card_print_requests_screen.022': 'Total',
  'screens_admin_card_print_requests_screen.023': 'Approve',
  'screens_admin_card_print_requests_screen.024': 'Reject',
  'screens_admin_card_print_requests_screen.025': 'Start printing',
  'screens_admin_card_print_requests_screen.026': 'Ready for delivery',
  'screens_admin_card_print_requests_screen.027': 'Complete request',
  'screens_admin_card_print_requests_screen.028': 'Processing...',
  'screens_admin_customers_screen.001': 'Could not load customers',
  'screens_admin_customers_screen.002': 'Missing data',
  'screens_admin_customers_screen.003': 'User created',
  'screens_admin_customers_screen.004': 'Creation failed',
  'screens_admin_customers_screen.005': 'Add new user',
  'screens_admin_customers_screen.006': 'Username',
  'screens_admin_customers_screen.007': 'Full name',
  'screens_admin_customers_screen.008': 'Country code',
  'screens_admin_customers_screen.009': 'WhatsApp',
  'screens_admin_customers_screen.010': 'Cancel',
  'screens_admin_customers_screen.011': 'Saving...',
  'screens_admin_customers_screen.012': 'Create',
  'screens_admin_customers_screen.013': 'Resend WhatsApp credentials',
  'screens_admin_customers_screen.014': 'Cancel',
  'screens_admin_customers_screen.015': 'Send',
  'screens_admin_customers_screen.016': 'Account details resent.',
  'screens_admin_customers_screen.017': 'Customer Management',
  'screens_admin_customers_screen.018': 'Customer Management',
  'screens_admin_customers_screen.019': 'Visible now',
  'screens_admin_customers_screen.020': 'Total in system',
  'screens_admin_customers_screen.021': 'Customers',
  'screens_admin_customers_screen.022': 'Add user',
  'screens_admin_customers_screen.023': 'Search for a customer...',
  'screens_admin_customers_screen.024':
      'Username and WhatsApp number are required.',
  'screens_admin_customers_screen.025':
      'The user has been created successfully.',
  'screens_admin_customers_screen.026':
      'A temporary password will be generated and sent automatically to the provided WhatsApp number.',
  'screens_admin_customers_screen.027': 'Unable to determine the user account.',
  'screens_admin_customers_screen.028':
      'A new password and account details will be sent over WhatsApp to the linked number.',
  'screens_admin_customers_screen.029':
      'Search customers, add new users, and open each customer profile independently.',
  'screens_admin_customers_screen.030': '{count} customers',
  'screens_admin_customers_screen.031': '{count} accounts',
  'screens_admin_customers_screen.032':
      'All data here belongs only to customers and is loaded when this screen opens.',
  'screens_admin_customer_screen.001': 'Resend user details',
  'screens_admin_customer_screen.002': 'Cancel',
  'screens_admin_customer_screen.003': 'Confirm send',
  'screens_admin_customer_screen.004': 'Sent',
  'screens_admin_customer_screen.005': 'Could not send',
  'screens_admin_customer_screen.006': 'shwakil customer',
  'screens_admin_customer_screen.007': 'Overview',
  'screens_admin_customer_screen.008': 'Transactions',
  'screens_admin_customer_screen.009': 'Management & Fees',
  'screens_admin_customer_screen.010': 'Permissions',
  'screens_admin_customer_screen.011': 'Devices',
  'screens_admin_customer_screen.012': 'Quick actions',
  'screens_admin_customer_screen.013': 'Current balance',
  'screens_admin_customer_screen.014': 'Account status',
  'screens_admin_customer_screen.015': 'Disabled',
  'screens_admin_customer_screen.016': 'Active',
  'screens_admin_customer_screen.017': 'Contact details',
  'screens_admin_customer_screen.018': 'Username',
  'screens_admin_customer_screen.019': 'Full name',
  'screens_admin_customer_screen.020': 'WhatsApp',
  'screens_admin_customer_screen.021': 'Join date',
  'screens_admin_customer_screen.022': 'Basic customer',
  'screens_admin_customer_screen.023': 'Customer transactions',
  'screens_admin_customer_screen.024': 'All',
  'screens_admin_customer_screen.025': 'Near branches',
  'screens_admin_customer_screen.026': 'Outside branches',
  'screens_admin_customer_screen.027': 'No recent transactions.',
  'screens_admin_customer_screen.028': 'Account management & fees',
  'screens_admin_customer_screen.029': 'Verification status',
  'screens_admin_customer_screen.030': 'Restricted member',
  'screens_admin_customer_screen.031': 'Verified member',
  'screens_admin_customer_screen.032': 'Advanced member',
  'screens_admin_customer_screen.033': 'Unverified',
  'screens_admin_customer_screen.034': 'Pending',
  'screens_admin_customer_screen.035': 'Verified / active',
  'screens_admin_customer_screen.036': 'Rejected',
  'screens_admin_customer_screen.037': 'Account role',
  'screens_admin_customer_screen.038': 'Basic user',
  'screens_admin_customer_screen.039': 'Support team',
  'screens_admin_customer_screen.040': 'Technical admin',
  'screens_admin_customer_screen.041': 'Printing debt limit (?)',
  'screens_admin_customer_screen.042': 'Custom fees for this customer (%)',
  'screens_admin_customer_screen.043': 'Save changes',
  'screens_admin_customer_screen.044': 'Top-up',
  'screens_admin_customer_screen.045': 'Withdraw',
  'screens_admin_customer_screen.046': 'Transfer',
  'screens_admin_customer_screen.047': 'Redeem',
  'screens_admin_customer_screen.048': 'Resell',
  'screens_admin_customer_screen.049': 'Print request',
  'screens_admin_customer_screen.050': 'Card & admin permissions',
  'screens_admin_customer_screen.051': 'Issue balance cards',
  'screens_admin_customer_screen.052': 'Request card printing',
  'screens_admin_customer_screen.053': 'Issue sub-shekel cards',
  'screens_admin_customer_screen.054': 'Issue high-value cards',
  'screens_admin_customer_screen.055': 'Resell used cards',
  'screens_admin_customer_screen.056': 'Review print requests',
  'screens_admin_customer_screen.057': 'Prepare and print requests',
  'screens_admin_customer_screen.058': 'Finalize and deliver requests',
  'screens_admin_customer_screen.059': 'Manage other users',
  'screens_admin_customer_screen.060': 'Device policy & access points',
  'screens_admin_customer_screen.061': 'Maximum allowed devices',
  'screens_admin_customer_screen.062': 'Update device policy',
  'screens_admin_customer_screen.063': 'Active devices',
  'screens_admin_customer_screen.064': 'Unknown device',
  'screens_admin_customer_screen.065':
      'Customer details were updated successfully.',
  'screens_admin_customer_screen.066':
      'A new password will be generated, then the login details will be sent to the account WhatsApp. Continue?',
  'screens_admin_customer_screen.067':
      'A new password was created and the user details were sent via WhatsApp.',
  'screens_admin_customer_screen.068':
      'Resending user details through WhatsApp will automatically generate a new password before sending.',
  'screens_admin_customer_screen.069':
      'Review financial transactions and activity related to this customer.',
  'screens_admin_customer_screen.070': 'No devices are linked to this account.',
  'screens_admin_customer_screen.071': 'Device ID: {id}',
  'screens_admin_dashboard_screen.001': 'Admin Center',
  'screens_admin_dashboard_screen.002': 'Quick Admin Hub',
  'screens_balance_screen.002':
      'You do not have permission to transfer balance.',
  'screens_balance_screen.003': 'Transfer balance',
  'screens_balance_screen.004': 'Send transfer',
  'screens_balance_screen.005': 'Notes',
  'screens_balance_screen.006': 'Transfer failed',
  'screens_balance_screen.007':
      'Withdrawals require a verified account and withdrawal permission.',
  'screens_balance_screen.008': 'Withdrawal request submitted successfully.',
  'screens_balance_screen.009': 'Withdrawal request failed',
  'screens_balance_screen.010':
      'You do not have permission to top up other users.',
  'screens_balance_screen.011': 'Top up balance',
  'screens_balance_screen.012': 'Top up',
  'screens_balance_screen.013': 'Notes',
  'screens_balance_screen.014': 'Enter the amount to add to the selected user.',
  'screens_balance_screen.015':
      'Balance was added and the user was notified successfully.',
  'screens_balance_screen.016': 'Balance was added successfully.',
  'screens_balance_screen.017': 'Top-up failed',
  'screens_balance_screen.018': 'Error',
  'screens_balance_screen.019': 'Success',
  'screens_balance_screen.020': 'Balance',
  'screens_balance_screen.021': 'Transaction history',
  'screens_balance_screen.022':
      'Review your latest movements and account activity.',
  'screens_balance_screen.023': 'Current balance',
  'screens_balance_screen.024': 'Available printing balance',
  'screens_balance_screen.025': 'Debt: {debt} of {limit}',
  'screens_balance_screen.026': 'Quick actions',
  'screens_balance_screen.027':
      'No quick actions are available with your current permissions.',
  'screens_balance_screen.028': 'Choose an action to continue.',
  'screens_balance_screen.029': 'Top-up request',
  'screens_balance_screen.030': 'Withdrawal request',
  'screens_balance_screen.031':
      'No extra actions are available for this account right now.',
  'screens_balance_screen.032':
      'Verify your account to unlock withdrawals and more actions.',
  'screens_balance_screen.033': 'Account summary',
  'screens_balance_screen.034': 'Role',
  'screens_balance_screen.035': 'Verification',
  'screens_balance_screen.036': 'Verified',
  'screens_balance_screen.037': 'Not verified',
  'screens_balance_screen.038': 'Transfer access',
  'screens_balance_screen.039': 'Available',
  'screens_balance_screen.040': 'Unavailable',
  'screens_balance_screen.041': 'Withdrawal access',
  'screens_balance_screen.042': 'User management',
  'screens_balance_screen.043': 'Card scan access',
  'screens_balance_screen.044': 'All',
  'screens_balance_screen.045': 'Near branches',
  'screens_balance_screen.046': 'Outside branches',
  'screens_balance_screen.047': 'Printing debt',
  'screens_balance_screen.048': 'No transactions yet',
  'screens_balance_screen.049': 'Transfer completed',
  'screens_balance_screen.050':
      'The transfer was processed successfully and your balance details were updated.',
  'screens_balance_screen.051': 'Close',
  'screens_balance_screen.052': 'Top-up requests unavailable',
  'screens_balance_screen.053':
      'Top-up requests are currently disabled for your account.',
  'screens_balance_screen.054': 'No payment methods available',
  'screens_balance_screen.055':
      'There are no payment methods available right now.',
  'screens_balance_screen.056':
      'Enter a valid amount and choose a payment method.',
  'screens_balance_screen.057': 'Request submitted',
  'screens_balance_screen.058':
      'Your top-up request was submitted successfully.',
  'screens_balance_screen.059':
      'Review the payment instructions carefully before submitting the request.',
  'screens_balance_screen.060': 'Payment method',
  'screens_balance_screen.061': 'Payment number: {number}',
  'screens_balance_screen.062': 'Transferred amount',
  'screens_balance_screen.063': 'Sender name',
  'screens_balance_screen.064': 'Sender phone number',
  'screens_balance_screen.065': 'Transfer reference',
  'screens_balance_screen.066': 'Transfer time',
  'screens_balance_screen.067': 'Example: 2026-04-10 14:30',
  'screens_balance_screen.068': 'Notes',
  'screens_balance_screen.069': 'Cancel',
  'screens_balance_screen.070': 'Sending...',
  'screens_balance_screen.071': 'Submit request',
  'screens_balance_screen.072': 'Could not load request options',
  'screens_balance_screen.073': 'Enter a username or full name to search.',
  'screens_balance_screen.074': 'No matching users were found.',
  'screens_balance_screen.075': 'Enter a phone number to look up the account.',
  'screens_balance_screen.076': 'Account found and selected successfully.',
  'screens_balance_screen.077': 'No account was found for this phone number.',
  'screens_balance_screen.078':
      'Search by username, or find the account directly by phone number.',
  'screens_balance_screen.079': 'Search for the user by username.',
  'screens_balance_screen.080': 'Username or full name',
  'screens_balance_screen.081': 'Searching...',
  'screens_balance_screen.082': 'Search',
  'screens_balance_screen.083': 'Find account by phone number',
  'screens_balance_screen.084': 'Country code',
  'screens_balance_screen.085': 'Phone number',
  'screens_balance_screen.086': 'Checking...',
  'screens_balance_screen.087': 'Verify number',
  'screens_balance_screen.088': 'Verify',
  'screens_balance_screen.089': 'User ID: {id}',
  'screens_balance_screen.090': 'User ID: {id} • Balance: {balance}',
  'screens_balance_screen.091': 'Selected account',
  'screens_balance_screen.092': 'WhatsApp number',
  'screens_balance_screen.093': 'Amount',
  'screens_balance_screen.094':
      'Select an account first using the phone lookup.',
  'screens_balance_screen.095':
      'Select an account first from the search results.',
  'screens_balance_screen.096': 'Bank account number',
  'screens_balance_screen.097': 'Wallet number or username',
  'screens_balance_screen.098':
      'Review the withdrawal details before sending the request.',
  'screens_balance_screen.099': 'Withdrawal destination',
  'screens_balance_screen.100': 'Wallet',
  'screens_balance_screen.101': 'Bank transfer',
  'screens_balance_screen.102': 'Enter the amount you want to withdraw.',
  'screens_balance_screen.103': 'Account holder name',
  'screens_balance_screen.104': 'Bank name',
  'screens_balance_screen.105': 'Enter a valid withdrawal amount.',
  'screens_balance_screen.106':
      'Account number and account holder name are required.',
  'screens_balance_screen.107':
      'Enter the bank name for bank transfer withdrawals.',
  'screens_admin_device_requests_screen.001': 'Device Requests',
  'screens_admin_device_requests_screen.002': 'Device requests',
  'screens_admin_device_requests_screen.003': 'Pending requests',
  'screens_admin_locations_screen.001': 'Could not load branches',
  'screens_admin_locations_screen.002': 'Missing data',
  'screens_admin_locations_screen.003': 'Could not save',
  'screens_admin_locations_screen.004': 'Add branch',
  'screens_admin_locations_screen.005': 'Edit branch',
  'screens_admin_locations_screen.006': 'Branch name',
  'screens_admin_locations_screen.007': 'Address',
  'screens_admin_locations_screen.008': 'Phone',
  'screens_admin_locations_screen.009': 'Type',
  'screens_admin_locations_screen.010': 'Latitude',
  'screens_admin_locations_screen.011': 'Longitude',
  'screens_admin_locations_screen.012': 'Display order',
  'screens_admin_locations_screen.013': 'Active',
  'screens_admin_locations_screen.014': 'Cancel',
  'screens_admin_locations_screen.015': 'Saving...',
  'screens_admin_locations_screen.016': 'Save',
  'screens_admin_locations_screen.017': 'Could not delete',
  'screens_admin_locations_screen.018': 'Branches & Locations',
  'screens_admin_locations_screen.019': 'Branches & locations',
  'screens_admin_locations_screen.020': 'Supported branches',
  'screens_admin_locations_screen.021': 'Add branch',
  'screens_admin_permissions_screen.001': 'Saved',
  'screens_admin_permissions_screen.002': 'Could not save',
  'screens_admin_permissions_screen.003': 'Permission Templates',
  'screens_admin_permissions_screen.004': 'Saving...',
  'screens_admin_permissions_screen.005': 'Save',
  'screens_admin_permissions_screen.006': 'Public Pages',
  'screens_admin_permissions_screen.007': 'Cards & Operations',
  'screens_admin_permissions_screen.008': 'Administration & Follow-up',
  'screens_admin_permissions_screen.009': 'View balance screen',
  'screens_admin_permissions_screen.010': 'View transactions',
  'screens_admin_permissions_screen.011': 'View cards',
  'screens_admin_permissions_screen.012': 'View quick transfer',
  'screens_admin_permissions_screen.013': 'View support',
  'screens_admin_permissions_screen.014': 'View agents and locations',
  'screens_admin_permissions_screen.015': 'View usage policy',
  'screens_admin_permissions_screen.016': 'View security settings',
  'screens_admin_permissions_screen.017': 'View account settings',
  'screens_admin_permissions_screen.018': 'Allow verification requests',
  'screens_admin_permissions_screen.019': 'Issue cards',
  'screens_admin_permissions_screen.020': 'Issue sub-shekel cards',
  'screens_admin_permissions_screen.021': 'Issue high-value cards',
  'screens_admin_permissions_screen.022': 'Issue private cards',
  'screens_admin_permissions_screen.023': 'Delete cards',
  'screens_admin_permissions_screen.024': 'Resell cards',
  'screens_admin_permissions_screen.025': 'Request card printing',
  'screens_admin_permissions_screen.026': 'Scan cards',
  'screens_admin_permissions_screen.027': 'Transfer funds',
  'screens_admin_permissions_screen.028': 'Withdraw and redeem',
  'screens_admin_permissions_screen.029': 'View customers',
  'screens_admin_permissions_screen.030': 'Lookup members',
  'screens_admin_permissions_screen.031': 'Manage users',
  'screens_admin_permissions_screen.032': 'Manage locations',
  'screens_admin_permissions_screen.033': 'Manage system settings',
  'screens_admin_permissions_screen.034': 'Review withdrawals',
  'screens_admin_permissions_screen.035': 'Review top-ups',
  'screens_admin_permissions_screen.036': 'Review devices',
  'screens_admin_permissions_screen.037': 'Review print requests',
  'screens_admin_permissions_screen.038': 'Prepare print requests',
  'screens_admin_permissions_screen.039': 'Finalize print requests',
  'screens_admin_permissions_screen.040': 'Export customer transactions',
  'screens_admin_system_settings_screen.001': 'Saved',
  'screens_admin_system_settings_screen.002': 'Could not save',
  'screens_admin_system_settings_screen.003': 'Missing data',
  'screens_admin_system_settings_screen.004': 'Could not save',
  'screens_admin_system_settings_screen.005': 'Add top-up method',
  'screens_admin_system_settings_screen.006': 'Edit top-up method',
  'screens_admin_system_settings_screen.007': 'Title',
  'screens_admin_system_settings_screen.008': 'Image URL',
  'screens_admin_system_settings_screen.009': 'Display order',
  'screens_admin_system_settings_screen.010': 'Description',
  'screens_admin_system_settings_screen.011': 'Active',
  'screens_admin_system_settings_screen.012': 'Cancel',
  'screens_admin_system_settings_screen.013': 'Saving...',
  'screens_admin_system_settings_screen.014': 'Save',
  'screens_admin_system_settings_screen.015': 'Could not delete',
  'screens_admin_system_settings_screen.016': 'System Settings',
  'screens_admin_system_settings_screen.017': 'System settings',
  'screens_admin_system_settings_screen.018': 'Contact Details',
  'screens_admin_system_settings_screen.019': 'Title',
  'screens_admin_system_settings_screen.020': 'Support WhatsApp',
  'screens_admin_system_settings_screen.021': 'Email',
  'screens_admin_system_settings_screen.022': 'Address',
  'screens_admin_system_settings_screen.023': 'Web URL',
  'screens_admin_system_settings_screen.024': 'Top-up Requests',
  'screens_admin_system_settings_screen.025': 'Add method',
  'screens_admin_system_settings_screen.026': 'Usage Policy',
  'screens_admin_system_settings_screen.027': 'Title',
  'screens_admin_system_settings_screen.028': 'Content',
  'screens_admin_system_settings_screen.029': 'Top-up fee',
  'screens_admin_system_settings_screen.030': 'Transfer fee',
  'screens_admin_system_settings_screen.031': 'Redeem fee',
  'screens_admin_system_settings_screen.032': 'Resell fee',
  'screens_admin_system_settings_screen.033': 'Print request fee',
  'screens_admin_system_settings_screen.034': 'Save settings',
  'screens_forgot_password_screen.001': 'Invalid birth date.',
  'screens_forgot_password_screen.002': 'Invalid phone number.',
  'screens_forgot_password_screen.003': 'Invalid verification code.',
  'screens_forgot_password_screen.004': 'Select birth date',
  'screens_forgot_password_screen.005': 'Cancel',
  'screens_forgot_password_screen.006': 'Confirm',
  'screens_forgot_password_screen.007': 'Error',
  'screens_forgot_password_screen.008': 'Sent successfully',
  'screens_forgot_password_screen.009': 'Error',
  'screens_forgot_password_screen.010': 'Error',
  'screens_forgot_password_screen.011': 'Account found',
  'screens_forgot_password_screen.012': 'Error',
  'screens_forgot_password_screen.013': 'Error',
  'screens_forgot_password_screen.014': 'Success',
  'screens_forgot_password_screen.015': 'Error',
  'screens_forgot_password_screen.016': 'Reset Password',
  'screens_forgot_password_screen.017': 'Reset Password',
  'screens_forgot_password_screen.018': 'Need help?',
  'screens_forgot_password_screen.019': 'National ID',
  'screens_forgot_password_screen.020': 'Birth date',
  'screens_forgot_password_screen.021': 'Select country',
  'screens_forgot_password_screen.022': 'Phone number',
  'screens_forgot_password_screen.023': 'Searching...',
  'screens_forgot_password_screen.024': 'Find account',
  'screens_forgot_password_screen.025': 'Sending...',
  'screens_forgot_password_screen.026': 'Send code',
  'screens_forgot_password_screen.027': 'Verification code',
  'screens_forgot_password_screen.028': 'Updating...',
  'screens_forgot_password_screen.029': 'Secure account recovery',
  'screens_forgot_password_screen.030':
      'Please enter the username or phone number.',
  'screens_forgot_password_screen.031':
      'Username must be between 3 and 64 characters.',
  'screens_forgot_password_screen.032':
      'Username contains unsupported characters.',
  'screens_forgot_password_screen.033':
      'Please fill in the national ID, birth date, and phone number.',
  'screens_forgot_password_screen.034':
      'National ID must contain only digits or hyphens.',
  'screens_forgot_password_screen.035':
      'Birth date must be in YYYY-MM-DD format.',
  'screens_forgot_password_screen.036':
      'Password must be between 8 and 64 characters.',
  'screens_forgot_password_screen.037':
      'Password must contain both letters and numbers.',
  'screens_forgot_password_screen.038':
      'A recovery code has been sent to the account WhatsApp. The password will not change without the code.',
  'screens_forgot_password_screen.039': 'Match found. Username: {username}',
  'screens_forgot_password_screen.040':
      'Your password has been reset. You can log in now.',
  'screens_forgot_password_screen.041':
      'Find the account first, then request the recovery code, and finally set a new password.',
  'screens_forgot_password_screen.042':
      'If your data does not match or you lost access to the linked number, contact support using this number.',
  'screens_forgot_password_screen.043': 'Find account by identity',
  'screens_forgot_password_screen.044': 'Example: 1995-04-21',
  'screens_forgot_password_screen.045': 'Username or phone number',
  'screens_forgot_password_screen.046': 'You can use either one.',
  'screens_forgot_password_screen.047': 'Debug code: {code}',
  'screens_forgot_password_screen.048': 'New password',
  'screens_forgot_password_screen.049': 'Save new password',
  'screens_forgot_password_screen.050':
      'Find the account, request the code, then set a new password through clear and quick steps.',
  'screens_home_screen.001': 'Cancel',
  'screens_home_screen.002': 'shwakil',
  'screens_home_screen.003': 'Log Out',
  'screens_home_screen.004': 'All Services',
  'screens_home_screen.005': 'Choose your service.',
  'screens_home_screen.006': 'Welcome',
  'screens_home_screen.007': 'Your account is ready',
  'screens_home_screen.008': 'Quick Services',
  'screens_home_screen.009': 'Verified account',
  'screens_home_screen.010': 'Unverified account',
  'screens_home_screen.011': 'Barcode Scan',
  'screens_home_screen.012': 'Open Camera',
  'screens_home_screen.013': 'Point the camera at the barcode.',
  'screens_home_screen.014': 'Scan Barcode',
  'screens_home_screen.015': 'Check the card.',
  'screens_home_screen.016': 'Check the card or resell it.',
  'screens_home_screen.017': 'Balance',
  'screens_home_screen.018': 'Balance and transactions.',
  'screens_home_screen.019': 'Issue Cards',
  'screens_home_screen.020': 'Create new cards.',
  'screens_home_screen.021': 'Quick Transfer',
  'screens_home_screen.022': 'Instant transfer.',
  'screens_home_screen.023': 'Cards Archive',
  'screens_home_screen.024': 'View and print cards.',
  'screens_home_screen.025': 'Print Request',
  'screens_home_screen.026': 'Send and track card print requests.',
  'screens_home_screen.027': 'Transactions',
  'screens_home_screen.028': 'Movement history.',
  'screens_home_screen.029': 'Security Settings',
  'screens_home_screen.030': 'Manage your protection.',
  'screens_home_screen.031': 'Welcome, {name}',
  'screens_home_screen.032': 'All your services in one place.',
  'screens_home_screen.033': 'Choose a service and get started instantly.',
  'screens_home_screen.034': '{count} services available',
  'screens_home_screen.035': 'Open the camera to scan the card.',
  'screens_home_screen.036': 'View your available balance.',
  'screens_home_screen.037': 'Issue a card',
  'screens_home_screen.038': 'Create a new card quickly.',
  'screens_home_screen.039': 'Quick transfer',
  'screens_home_screen.040': 'Send transfers instantly.',
  'screens_home_screen.041': 'Cards archive',
  'screens_home_screen.042': 'View and manage cards.',
  'screens_home_screen.043': 'Print requests',
  'screens_home_screen.044': 'Send and track print requests.',
  'screens_home_screen.045': 'Transactions',
  'screens_home_screen.046': 'Review movement history.',
  'screens_home_screen.047': 'Security settings',
  'screens_home_screen.048': 'Manage your account protection.',
  'screens_home_screen.049': 'Scan the card',
  'screens_inventory_screen.001': 'Digital Card Inventory',
  'screens_inventory_screen.002': 'Card Inventory',
  'screens_inventory_screen.003': 'Request card printing',
  'screens_inventory_screen.004': '{totalCards} cards',
  'screens_inventory_screen.005': 'New',
  'screens_inventory_screen.006': 'Used',
  'screens_inventory_screen.007': 'Archived',
  'screens_inventory_screen.008': 'Print',
  'screens_inventory_screen.009': 'Delete and refund',
  'screens_inventory_screen.010': 'shwakil',
  'screens_inventory_screen.011': 'Permanent deletion?',
  'screens_inventory_screen.012': 'Cancel',
  'screens_inventory_screen.013': 'Delete',
  'screens_login_screen.001': 'Password is too long.',
  'screens_login_screen.002': 'Error',
  'screens_login_screen.003': 'Success',
  'screens_login_screen.004': 'Log In',
  'screens_login_screen.005': 'Username or phone',
  'screens_login_screen.006': 'Password',
  'screens_login_screen.007': 'Sign In',
  'screens_login_screen.008': 'Create account',
  'screens_login_screen.009': 'Please enter your username and password.',
  'screens_login_screen.010': 'Username must be between 3 and 64 characters.',
  'screens_login_screen.011': 'Username contains unsupported characters.',
  'screens_login_screen.012': 'For user {username}: {message}',
  'screens_login_screen.013':
      'Enter your credentials and move directly to verification.',
  'screens_login_screen.014': 'Registration is currently disabled',
  'screens_login_screen.015':
      'To create a new account, contact admin on WhatsApp: {whatsapp}',
  'screens_login_screen.016': 'To create a new account, contact admin.',
  'screens_onboarding_screen.001': 'Skip',
  'screens_onboarding_screen.002': 'Get Started',
  'screens_onboarding_screen.003': 'Next',
  'screens_otp_verification_screen.001': 'Incomplete code',
  'screens_otp_verification_screen.002': 'Completed',
  'screens_otp_verification_screen.003': 'Verification failed',
  'screens_otp_verification_screen.004': 'Code sent again',
  'screens_otp_verification_screen.005': 'Could not resend',
  'screens_otp_verification_screen.006': 'Verify Code',
  'screens_otp_verification_screen.007': 'Username',
  'screens_otp_verification_screen.008': 'WhatsApp',
  'screens_otp_verification_screen.009': 'Verification code',
  'screens_otp_verification_screen.010': 'Debug code: {debugCode}',
  'screens_otp_verification_screen.011': 'Complete registration',
  'screens_otp_verification_screen.012': 'Confirm sign in',
  'screens_otp_verification_screen.013': 'Sending...',
  'screens_otp_verification_screen.014': 'Resend',
  'screens_quick_transfer_screen.001': 'Admin',
  'screens_quick_transfer_screen.002': 'Support',
  'screens_quick_transfer_screen.003': 'User',
  'screens_quick_transfer_screen.004': 'User',
  'screens_quick_transfer_screen.005': 'Scan recipient code',
  'screens_quick_transfer_screen.006': 'Cancel',
  'screens_quick_transfer_screen.007': 'Unsupported QR code.',
  'screens_quick_transfer_screen.008': 'You cannot transfer to yourself.',
  'screens_quick_transfer_screen.009': 'User',
  'screens_quick_transfer_screen.010': 'Phone required',
  'screens_quick_transfer_screen.011': 'You cannot transfer to yourself.',
  'screens_quick_transfer_screen.012': 'Transfer complete',
  'screens_quick_transfer_screen.013': 'Transfer balance',
  'screens_quick_transfer_screen.014': 'Cancel',
  'screens_quick_transfer_screen.015': 'Confirm',
  'screens_quick_transfer_screen.016': 'Send Balance',
  'screens_quick_transfer_screen.017': 'Country code',
  'screens_quick_transfer_screen.018': 'Find recipient',
  'screens_quick_transfer_screen.019': 'Search result',
  'screens_quick_transfer_screen.020': 'Or use QR',
  'screens_quick_transfer_screen.021': 'Open camera and scan',
  'screens_quick_transfer_screen.022': 'Balance receiving code',
  'screens_register_screen.001': 'Check your data',
  'screens_register_screen.002': 'Username is required.',
  'screens_register_screen.003': 'Invalid national ID number.',
  'screens_register_screen.004': 'Please select your birth date.',
  'screens_register_screen.005': 'Invalid birth date.',
  'screens_register_screen.006': 'Password is required.',
  'screens_register_screen.007': 'Check your data',
  'screens_register_screen.008': 'Could not start registration',
  'screens_register_screen.009': 'Create a New Account',
  'screens_register_screen.010': 'Basic Information',
  'screens_register_screen.011': 'Full name',
  'screens_register_screen.012': 'Username in English',
  'screens_register_screen.013': 'National ID',
  'screens_register_screen.014': 'Birth date',
  'screens_register_screen.015': 'Contact Details',
  'screens_register_screen.016': 'Country',
  'screens_register_screen.017': 'WhatsApp number',
  'screens_register_screen.018': 'Referral phone number',
  'screens_register_screen.019': 'Account Security',
  'screens_register_screen.020': 'Password',
  'screens_register_screen.021': 'Confirm password',
  'screens_register_screen.022': 'Previous',
  'screens_register_screen.023': 'Send verification code',
  'screens_register_screen.024': 'Next',
  'screens_register_screen.025': 'Details',
  'screens_register_screen.026': 'Contact',
  'screens_register_screen.027': 'Security',
  'screens_register_screen.028': 'Admin contact',
  'screens_register_screen.029': 'Please enter your full name correctly.',
  'screens_register_screen.030':
      'Username must use English letters or numbers only, with . _ - + and @ allowed.',
  'screens_register_screen.031': 'Please enter a valid WhatsApp number.',
  'screens_register_screen.032': 'Referral phone number is invalid.',
  'screens_register_screen.033': 'Password must be at least 8 characters.',
  'screens_register_screen.034': 'Password must contain at least one letter.',
  'screens_register_screen.035': 'Password must contain at least one symbol.',
  'screens_register_screen.036': 'Password confirmation is required.',
  'screens_register_screen.037': 'Password confirmation does not match.',
  'screens_register_screen.038':
      'You must accept the terms and conditions to continue.',
  'screens_register_screen.039':
      'Complete the required registration details and we will send a verification code to finish creating your account.',
  'screens_register_screen.040': 'Already have an account? Log in',
  'screens_register_screen.041':
      'Password must be at least 8 characters and include at least one letter and one symbol.',
  'screens_register_screen.042':
      'I agree to the displayed terms, policies, and fees.',
  'screens_register_screen.043': 'Registration is currently disabled',
  'screens_register_screen.044':
      'You can contact the administration to request a new account or ask them to re-enable registration.',
  'screens_register_screen.045':
      'Message the administration directly on WhatsApp to request account creation or registration access.',
  'screens_register_screen.046': 'Back to login',
  'screens_topup_requests_screen.001': 'Top-up Requests',
  'screens_topup_requests_screen.002': 'Top-up Requests',
  'screens_topup_requests_screen.003': '{pending} pending',
  'screens_topup_requests_screen.004': 'All',
  'screens_topup_requests_screen.005': 'Pending',
  'screens_topup_requests_screen.006': 'Approved',
  'screens_topup_requests_screen.007': 'Rejected',
  'screens_topup_requests_screen.008': 'Payment method',
  'screens_topup_requests_screen.009': 'Method number',
  'screens_topup_requests_screen.010': 'Sender name',
  'screens_topup_requests_screen.011': 'Sender phone',
  'screens_topup_requests_screen.012': 'Transfer reference',
  'screens_topup_requests_screen.013': 'Notes',
  'screens_topup_requests_screen.014': 'Approve top-up',
  'screens_topup_requests_screen.015': 'Reject',
  'screens_topup_requests_screen.016': 'Approved',
  'screens_topup_requests_screen.017': 'Rejected',
  'screens_topup_requests_screen.018': 'Under review',
  'screens_topup_requests_screen.019': 'No matching requests right now',
  'screens_topup_requests_screen.020': 'Reject top-up request',
  'screens_topup_requests_screen.021': 'Rejection reason',
  'screens_topup_requests_screen.022': 'Cancel',
  'screens_topup_requests_screen.023': 'Confirm rejection',
  'screens_topup_requests_screen.024': 'The request has been rejected.',
  'screens_transactions_screen.001': 'Could not load transaction history',
  'screens_transactions_screen.002': 'Error',
  'screens_transactions_screen.003': 'Success',
  'screens_transactions_screen.004': 'Could not export transactions',
  'screens_transactions_screen.005': 'Transactions',
  'screens_transactions_screen.006': 'Account statement',
  'screens_transactions_screen.007': 'Current balance',
  'screens_transactions_screen.008': 'Total credits',
  'screens_transactions_screen.009': 'Total debits',
  'screens_transactions_screen.010': 'Net period',
  'screens_transactions_screen.011': 'Refresh history',
  'screens_transactions_screen.012': 'Export CSV',
  'screens_transactions_screen.013': 'Search & filters',
  'screens_transactions_screen.014': 'Search transactions',
  'screens_transactions_screen.015': 'Date range',
  'screens_transactions_screen.016': 'All',
  'screens_transactions_screen.017': 'Today',
  'screens_transactions_screen.018': 'Last 7 days',
  'screens_transactions_screen.019': 'This month',
  'screens_transactions_screen.020': 'Location & type',
  'screens_transactions_screen.021': 'All',
  'screens_transactions_screen.022': 'Near branch',
  'screens_transactions_screen.023': 'Outside branches',
  'screens_transactions_screen.024': 'Printing debt',
  'screens_transactions_screen.025': 'Date range',
  'screens_transactions_screen.026': 'All',
  'screens_transactions_screen.027': 'Today',
  'screens_transactions_screen.028': 'Last 7 days',
  'screens_transactions_screen.029': 'This month',
  'screens_transactions_screen.030': 'Location & type',
  'screens_transactions_screen.031': 'All',
  'screens_transactions_screen.032': 'Near branch',
  'screens_transactions_screen.033': 'Outside branches',
  'screens_transactions_screen.034': 'Printing debt',
  'screens_transactions_screen.035': 'No transactions available',
  'screens_withdrawal_requests_screen.001': 'Withdrawal Requests',
  'screens_withdrawal_requests_screen.002': 'Track withdrawal requests',
  'screens_withdrawal_requests_screen.003': '{pending} pending',
  'screens_withdrawal_requests_screen.004': 'Search for a request...',
  'screens_withdrawal_requests_screen.005': 'All',
  'screens_withdrawal_requests_screen.006': 'Pending',
  'screens_withdrawal_requests_screen.007': 'Approved',
  'screens_withdrawal_requests_screen.008': 'Rejected',
  'screens_withdrawal_requests_screen.009': 'Transfer destination',
  'screens_withdrawal_requests_screen.010': 'Beneficiary name',
  'screens_withdrawal_requests_screen.011': 'Account number',
  'screens_withdrawal_requests_screen.012': 'Bank name',
  'screens_withdrawal_requests_screen.013': 'Notes',
  'screens_withdrawal_requests_screen.014': 'Approve',
  'screens_withdrawal_requests_screen.015': 'Reject',
  'screens_withdrawal_requests_screen.016': 'Approved',
  'screens_withdrawal_requests_screen.017': 'Rejected',
  'screens_withdrawal_requests_screen.018': 'Under review',
  'screens_withdrawal_requests_screen.019': 'No matching requests right now',
  'screens_withdrawal_requests_screen.020': 'The request has been approved.',
  'screens_withdrawal_requests_screen.021': 'Reject request',
  'screens_withdrawal_requests_screen.022': 'Rejection reason',
  'screens_withdrawal_requests_screen.023': 'Cancel',
  'screens_withdrawal_requests_screen.024': 'Confirm rejection',
  'screens_withdrawal_requests_screen.025': 'The request has been rejected.',
  'widgets_app_sidebar.001': 'shwakil',
  'widgets_app_sidebar.002': 'Main',
  'widgets_app_sidebar.003': 'Home',
  'widgets_app_sidebar.004': 'Balance',
  'widgets_app_sidebar.005': 'Transactions',
  'widgets_app_sidebar.006': 'Cards',
  'widgets_app_sidebar.007': 'Print Requests',
  'widgets_app_sidebar.008': 'Scan Cards',
  'widgets_app_sidebar.009': 'Account',
  'widgets_app_sidebar.010': 'Account',
  'widgets_app_sidebar.011': 'Quick Transfer',
  'widgets_app_sidebar.012': 'Verify Account',
  'widgets_app_sidebar.013': 'Security',
  'widgets_app_sidebar.014': 'Admin',
  'widgets_app_sidebar.015': 'Admin Center',
  'widgets_app_sidebar.016': 'Device Requests',
  'widgets_app_sidebar.017': 'Top-up Requests',
  'widgets_app_sidebar.018': 'Branches & Locations',
  'widgets_app_sidebar.019': 'System Settings',
  'widgets_app_sidebar.020': 'More',
  'widgets_app_sidebar.021': 'Usage Policy',
  'widgets_app_sidebar.022': 'Support',
  'widgets_app_sidebar.023': 'Agents',
  'widgets_app_sidebar.024': 'Language',
  'widgets_app_sidebar.025': 'English / العربية',
  'widgets_app_sidebar.026': 'Log Out',
  'widgets_app_sidebar.027': 'Unverified',
  'widgets_app_sidebar.028': 'Verified',
  'widgets_app_sidebar.029': 'Under Review',
  'widgets_app_sidebar.030': 'Customer Management',
  'widgets_app_sidebar.031': 'Withdrawal Requests',
  'widgets_app_sidebar.032': 'Card Print Requests',
  'widgets_app_sidebar.033': 'Permission Templates',
  'widgets_app_sidebar.034': 'Tap to switch between Arabic and English',
  'widgets_shwakel_logo.001': 'shwakil',
  'widgets_admin_transaction_audit_card.001': 'Top-up',
  'widgets_admin_transaction_audit_card.002': 'Transfer sent',
  'widgets_admin_transaction_audit_card.003': 'Transfer received',
  'widgets_admin_transaction_audit_card.004': 'Card redeemed',
  'widgets_admin_transaction_audit_card.005': 'Card resold',
  'widgets_admin_transaction_audit_card.006': 'Cards issued',
  'widgets_admin_transaction_audit_card.007': 'Withdrawal request',
  'widgets_admin_transaction_audit_card.008': 'Withdrawal rejected',
  'widgets_admin_transaction_audit_card.009': 'Withdrawal completed',
  'widgets_admin_transaction_audit_card.010': 'Printing debt settlement',
  'widgets_admin_transaction_audit_card.011': 'Balance credit',
  'widgets_admin_transaction_audit_card.012': 'Application fee credit',
  'widgets_admin_transaction_audit_card.013': 'Unknown transaction',
  'widgets_admin_transaction_audit_card.014': 'By @{username}',
  'widgets_admin_transaction_audit_card.015': 'Sent to @{username}',
  'widgets_admin_transaction_audit_card.016': 'Received from @{username}',
  'widgets_admin_transaction_audit_card.017': 'For customer {name}',
  'widgets_admin_transaction_audit_card.018': 'Issued by @{username}',
  'widgets_admin_transaction_audit_card.019':
      'Used printing debt amount: {amount}',
  'widgets_admin_transaction_audit_card.020':
      'Credited to @{username} from application fees',
  'widgets_admin_transaction_audit_card.021':
      'Credited from @{username} as application fees',
  'widgets_admin_transaction_audit_card.022': 'Source: top-up fees',
  'widgets_admin_transaction_audit_card.023': 'Source: transfer fees',
  'widgets_admin_transaction_audit_card.024': 'Source: card redeem fees',
  'widgets_admin_transaction_audit_card.025': 'Source: card resale fees',
  'widgets_admin_transaction_audit_card.026': 'Waiting for withdrawal review',
  'widgets_admin_transaction_audit_card.027': 'Withdrawal was rejected',
  'widgets_admin_transaction_audit_card.028':
      'Withdrawal delivered successfully',
  'widgets_admin_transaction_audit_card.029': 'Rejected',
  'widgets_admin_transaction_audit_card.030': 'Near branch',
  'widgets_admin_transaction_audit_card.031': 'Outside branches',
  'widgets_admin_admin_customer_card.001': 'Verified',
  'widgets_admin_admin_customer_card.002': 'Under review',
  'widgets_admin_admin_customer_card.003': 'Unverified',
  'widgets_admin_admin_customer_card.004': 'Balance',
  'widgets_admin_admin_customer_card.005': 'Account type',
  'widgets_admin_admin_customer_card.006': 'Verification status',
  'widgets_admin_admin_customer_card.007': 'Admin',
  'widgets_admin_admin_customer_card.008': 'System administrator',
  'widgets_admin_admin_customer_card.009': 'Resend account details',
  'widgets_admin_transaction_filter_tabs.001': 'All',
  'widgets_admin_transaction_filter_tabs.002': 'Near branches',
  'widgets_admin_transaction_filter_tabs.003': 'Outside branches',
  'widgets_admin_admin_device_request_card.001': 'Unknown device',
  'widgets_admin_admin_device_request_card.002': 'ID unavailable',
  'widgets_admin_admin_device_request_card.003': 'Access request: {createdAt}',
  'widgets_admin_admin_device_request_card.004': 'Approve',
  'widgets_admin_admin_device_request_card.005': 'Reject',
  'widgets_admin_admin_location_card.001': 'Unknown branch',
  'widgets_admin_admin_location_card.002': 'No address available',
  'widgets_admin_admin_location_card.003': 'Branch',
  'widgets_admin_admin_location_card.004': 'Active',
  'widgets_admin_admin_location_card.005': 'Disabled',
  'widgets_admin_admin_pagination_footer.001': 'Previous',
  'widgets_admin_admin_pagination_footer.002': 'Next',
  'widgets_admin_admin_settings_group.001': 'Save settings',
  'screens_admin_dashboard_screen.description':
      'Welcome {name}. Each admin section now opens in its own screen and loads only its own data for a faster and clearer experience.',
  'screens_admin_device_requests_screen.load_error_title':
      'Could not load requests',
  'screens_admin_device_requests_screen.update_error_title':
      'Could not update request',
  'screens_admin_device_requests_screen.hero_subtitle':
      'This screen is dedicated to reviewing new device requests without loading extra admin data.',
  'screens_admin_device_requests_screen.section_subtitle':
      'Approve or reject device linking requests directly from this screen.',
  'screens_admin_device_requests_screen.empty_state':
      'There are no pending device requests right now.',
  'screens_admin_locations_screen.required_fields':
      'Branch name and address are required.',
  'screens_admin_locations_screen.hero_subtitle':
      'Location management now lives in a dedicated screen and loads only when opened.',
  'screens_admin_locations_screen.section_subtitle':
      'Add or edit locations from a dedicated fast screen.',
  'screens_admin_card_print_requests_screen.load_error_title':
      'Could not load requests',
  'screens_admin_card_print_requests_screen.update_error_title':
      'Could not update request',
  'screens_admin_card_print_requests_screen.file_unavailable_title':
      'File unavailable',
  'screens_admin_card_print_requests_screen.export_unavailable_message':
      'A PDF cannot be generated for this request yet because the cards have not been prepared inside the request.',
  'screens_admin_card_print_requests_screen.print_unavailable_message':
      'This request cannot be printed yet because the cards have not been prepared inside the request.',
  'screens_admin_card_print_requests_screen.pdf_generated_title':
      'PDF generated',
  'screens_admin_card_print_requests_screen.pdf_generated_message':
      'The request PDF was saved successfully at:\n{path}',
  'screens_admin_card_print_requests_screen.pdf_failed_title':
      'Could not generate PDF',
  'screens_admin_card_print_requests_screen.print_failed_title':
      'Printing failed',
  'screens_admin_card_print_requests_screen.hero_title':
      'Manage card print requests',
  'screens_admin_card_print_requests_screen.hero_subtitle':
      'This workflow is fully separated for reviewing, approving, printing, preparing, and completing card print requests.',
  'screens_admin_card_print_requests_screen.section_subtitle':
      'Filter, search, and follow each request based on its current stage.',
  'screens_admin_card_print_requests_screen.search_label':
      'Search by name, phone, or request number',
  'screens_admin_card_print_requests_screen.empty_state':
      'No matching requests at the moment.',
  'screens_admin_card_print_requests_screen.quantity_label': '{count} cards',
  'screens_admin_card_print_requests_screen.customer_notes':
      'Customer notes: {notes}',
  'screens_admin_card_print_requests_screen.print_now': 'Print now',
  'screens_admin_card_print_requests_screen.export_pdf': 'Export PDF',
  'screens_admin_card_print_requests_screen.pending_status': 'Review',
  'screens_device_unlock_screen.001': 'Incomplete PIN',
  'screens_device_unlock_screen.002': 'Enter the 4-digit PIN code.',
  'screens_device_unlock_screen.003': 'Incorrect code',
  'screens_device_unlock_screen.004': 'The PIN you entered is incorrect.',
  'screens_device_unlock_screen.005': 'Sign in with another account',
  'screens_device_unlock_screen.006': 'Unlock your secure device',
  'screens_device_unlock_screen.007':
      'Enter your PIN or use biometrics to continue.',
  'screens_device_unlock_screen.008': 'Use biometrics to continue to the app.',
  'screens_device_unlock_screen.009':
      'Welcome {username}, enter your PIN or use biometrics to continue.',
  'screens_device_unlock_screen.010':
      'Welcome {username}, use biometrics to continue to the app.',
  'screens_device_unlock_screen.011': 'PIN code',
  'screens_device_unlock_screen.012': 'Unlock with PIN',
  'screens_device_unlock_screen.013': 'Unlock with biometrics',
  'screens_security_settings_screen.001': 'Device Security',
  'screens_security_settings_screen.002': 'Remove trust from this device',
  'screens_security_settings_screen.003': 'Protection settings',
  'screens_security_settings_screen.004': 'Trusted device',
  'screens_security_settings_screen.005': 'Untrusted device',
  'screens_security_settings_screen.006': 'PIN enabled',
  'screens_security_settings_screen.007': 'PIN disabled',
  'screens_security_settings_screen.008': 'Biometrics enabled',
  'screens_security_settings_screen.009': 'Biometrics disabled',
  'screens_security_settings_screen.010': 'Biometrics',
  'screens_security_settings_screen.011': 'PIN code',
  'screens_security_settings_screen.012': 'OTP',
  'screens_security_settings_screen.013':
      'Manage PIN, biometrics, trusted devices, and relock settings from one place.',
  'screens_security_settings_screen.014': 'Security overview',
  'screens_security_settings_screen.015':
      'See verification status, device trust, and the latest sign-in method.',
  'screens_security_settings_screen.016': 'Device trust',
  'screens_security_settings_screen.017': 'Trusted',
  'screens_security_settings_screen.018': 'Untrusted',
  'screens_security_settings_screen.019': 'Local PIN',
  'screens_security_settings_screen.020': 'Enabled',
  'screens_security_settings_screen.021': 'Disabled',
  'screens_security_settings_screen.022':
      'You can use biometrics or PIN, and biometrics work even without PIN.',
  'screens_security_settings_screen.023':
      'You can enable biometrics directly even if you have not set a PIN.',
  'screens_security_settings_screen.024':
      'This device does not support biometrics or it is not configured in the system.',
  'screens_security_settings_screen.025': 'Last verification method',
  'screens_security_settings_screen.026': 'Trusted account on this device',
  'screens_security_settings_screen.027': 'Local unlock methods',
  'screens_security_settings_screen.028':
      'Enable PIN, biometrics, or both to speed up app access and confirm sensitive actions.',
  'screens_security_settings_screen.029': 'Change PIN',
  'screens_security_settings_screen.030': 'Set PIN',
  'screens_security_settings_screen.031':
      'Used to unlock the app and confirm sensitive operations.',
  'screens_security_settings_screen.032': 'Update',
  'screens_security_settings_screen.033': 'Set up',
  'screens_security_settings_screen.034': 'Enable biometrics',
  'screens_security_settings_screen.035': 'Automatic relock',
  'screens_security_settings_screen.036':
      'Choose when the app should request local verification again after staying in the background.',
  'screens_security_settings_screen.037': 'Relock the app after',
  'screens_security_settings_screen.038': 'Active devices',
  'screens_security_settings_screen.039':
      'You can remove any device and require it to verify again on the next sign-in.',
  'screens_security_settings_screen.040':
      'No active devices are currently visible.',
  'screens_security_settings_screen.041': 'Unknown device',
  'screens_security_settings_screen.042': 'Device ID: {id}',
  'screens_security_settings_screen.043': 'Current device',
  'screens_security_settings_screen.044': 'Delete device',
  'screens_security_settings_screen.045': 'Immediately',
  'screens_security_settings_screen.046': '{count} seconds',
  'screens_security_settings_screen.047': '{count} minutes',
  'screens_security_settings_screen.048': 'Delete device',
  'screens_security_settings_screen.049':
      'Do you want to remove this device from the active devices list?',
  'screens_security_settings_screen.050': 'Cancel',
  'screens_security_settings_screen.051': 'Delete',
  'screens_security_settings_screen.052': 'Deleted',
  'screens_security_settings_screen.053':
      'The device was removed from the account successfully.',
  'screens_security_settings_screen.054': 'Could not delete',
  'screens_security_settings_screen.055': 'Update PIN',
  'screens_security_settings_screen.056': 'New PIN',
  'screens_security_settings_screen.057': 'Enter 4 digits',
  'screens_security_settings_screen.058': 'Confirm code',
  'screens_security_settings_screen.059': 'Save',
  'screens_security_settings_screen.060': 'Invalid code',
  'screens_security_settings_screen.061':
      'Make sure you entered 4 matching digits.',
  'screens_security_settings_screen.062': 'Remove PIN',
  'screens_security_settings_screen.063':
      'Do you want to remove the local PIN from this device?',
  'screens_security_settings_screen.064': 'Remove',
  'screens_onboarding_screen.004': 'Your balance and services in one place',
  'screens_onboarding_screen.005': 'Faster card and transfer actions',
  'screens_onboarding_screen.006':
      'Trusted protection and a reliable experience',
  'screens_onboarding_screen.007':
      'Track your balance, create cards, and access daily operations from a clear and simple interface.',
  'screens_onboarding_screen.008':
      'The app is designed to reduce steps and speed up access to card creation, scanning, and transfers.',
  'screens_onboarding_screen.009':
      'Verification, account management, and sensitive actions are organized in a secure and user-friendly way.',
  'screens_otp_verification_screen.015':
      'Please enter the full verification code to continue.',
  'screens_otp_verification_screen.016':
      'Your account has been created successfully. You can log in now.',
  'screens_otp_verification_screen.017':
      'A new verification code has been sent to WhatsApp.',
  'screens_otp_verification_screen.018':
      'Enter the code sent to your WhatsApp to complete registration.',
  'screens_otp_verification_screen.019':
      'Enter the code sent to your WhatsApp to sign in securely.',
  'screens_otp_verification_screen.020':
      'You can resend the code in {count} seconds',
  'screens_otp_verification_screen.021':
      'Didn'
      't receive the code yet?',

  'screens_admin_permissions_screen.041':
      'From here you can define what this membership level can see and use across the app and admin panel.',

  'screens_inventory_screen.014':
      'Review issued cards, reprint them, or delete unused cards whenever needed.',

  'screens_inventory_screen.015': 'There are no cards in this section',

  'screens_inventory_screen.016': 'The print request has been sent.',

  'screens_inventory_screen.017':
      'The card will be deleted and the balance will be refunded to your account immediately.',

  'screens_inventory_screen.018':
      'The card was deleted and the value was refunded.',
  'screens_topup_requests_screen.025':
      'This screen is available for administrators only.',
  'screens_topup_requests_screen.026': 'Review top-up requests',
  'screens_topup_requests_screen.027':
      'Review transfer details and payment method before approving or rejecting the top-up request.',
  'screens_topup_requests_screen.028':
      'Search by username or reference number...',
  'screens_topup_requests_screen.029':
      'A proof image is required before approving the top-up request.',
  'screens_topup_requests_screen.030': 'The top-up request has been approved.',
  'screens_topup_requests_screen.031': 'Write a short note for the user',
  'screens_admin_system_settings_screen.035':
      'Settings have been saved successfully.',
  'screens_admin_system_settings_screen.036':
      'Title and transfer number are required.',
  'screens_admin_system_settings_screen.037': 'Account or wallet number',
  'screens_admin_system_settings_screen.038':
      'All administration settings were moved to a dedicated screen and load only when needed.',
  'screens_admin_system_settings_screen.039': 'Support and contact settings.',
  'screens_admin_system_settings_screen.040':
      'Registration & Transfer Settings',
  'screens_admin_system_settings_screen.041':
      'General policies and system limits.',
  'screens_admin_system_settings_screen.042': 'Allow new registration',
  'screens_admin_system_settings_screen.043':
      'Transfer limit for unverified accounts',
  'screens_admin_system_settings_screen.044': 'Minimum supported version',
  'screens_admin_system_settings_screen.045': 'Latest available version',
  'screens_admin_system_settings_screen.046':
      'Enable the service and manage payment methods.',
  'screens_admin_system_settings_screen.047': 'Enable top-up requests',
  'screens_admin_system_settings_screen.048':
      'Top-up instructions for customer',
  'screens_admin_system_settings_screen.049':
      'No top-up methods have been added yet.',
  'screens_admin_system_settings_screen.050':
      'Update the policy text displayed inside the app.',
  'screens_admin_system_settings_screen.051': 'Android URL',
  'screens_admin_system_settings_screen.052': 'iOS URL',
  'screens_withdrawal_requests_screen.026':
      'Review transfer requests to bank accounts or digital wallets before approval.',
  'screens_withdrawal_requests_screen.027':
      'A proof image is required before approving the withdrawal request.',
  'screens_withdrawal_requests_screen.028': 'Write a short note for the user',
  'widgets_support_contact_card.001': 'Support number copied',
  'widgets_support_contact_card.002': 'Could not open WhatsApp on this device',
  'widgets_support_contact_card.003': 'Support & Contact',
  'widgets_support_contact_card.004': 'Open WhatsApp',
  'widgets_support_contact_card.005': 'Copy number',
  'screens_usage_policy_screen.001': 'Usage Policy',
  'screens_usage_policy_screen.002':
      'We explain here the terms that govern the use of the app and services in a clear and direct way.',
  'screens_usage_policy_screen.003': 'No usage policy is currently available.',
  'screens_usage_policy_screen.004': 'Legal charter and privacy',
  'screens_usage_policy_screen.005':
      'Our commitment to providing safe and well-organized services for all shwakil users.',
  'screens_supported_locations_screen.001': 'Branches & Service Centers',
  'screens_supported_locations_screen.002': 'shwakil interactive map',
  'screens_supported_locations_screen.003':
      'Find the nearest agent or approved top-up point in your area with automatic distance-based sorting.',
  'screens_supported_locations_screen.004': '{count} available locations',
  'screens_supported_locations_screen.005': 'Sorted by distance',
  'screens_supported_locations_screen.006': 'General order',
  'screens_supported_locations_screen.007':
      'Locations were automatically sorted by distance from your current location.',
  'screens_supported_locations_screen.008': 'shwakil branch',
  'screens_supported_locations_screen.009': 'Approved service point',
  'screens_supported_locations_screen.010': 'Open in maps',
  'screens_supported_locations_screen.011':
      'No locations are currently registered',
  'screens_supported_locations_screen.012':
      'You can come back later or pull to refresh the screen.',
  'screens_supported_locations_screen.013': '{count} m',
  'screens_supported_locations_screen.014': '{count} km',
  'screens_scan_card_screen.001': 'Scan barcode',
  'screens_scan_card_screen.002': 'Search for a card',
  'screens_scan_card_screen.003': 'Enter the barcode or open the camera.',
  'screens_scan_card_screen.004': 'Barcode number',
  'screens_scan_card_screen.005': 'Open camera',
  'screens_scan_card_screen.006': 'Search',
  'screens_scan_card_screen.007': 'Card details',
  'screens_scan_card_screen.008':
      'Search for a card or use the camera to display its details.',
  'screens_scan_card_screen.009': 'Hide card details',
  'screens_scan_card_screen.010': 'Show card details',
  'screens_scan_card_screen.011': 'Reactivate card',
  'screens_scan_card_screen.012': 'Card scanning',
  'screens_scan_card_screen.013': 'Current balance: {balance}',
  'screens_scan_card_screen.014': 'Scan result',
  'screens_scan_card_screen.015': 'Card already used',
  'screens_scan_card_screen.016': 'Card is valid and ready',
  'screens_scan_card_screen.017':
      'This card has already been used and cannot be redeemed again.',
  'screens_scan_card_screen.018':
      'This card is valid and can be redeemed or reviewed.',
  'screens_scan_card_screen.019': 'Status',
  'screens_scan_card_screen.020': 'Value',
  'screens_scan_card_screen.021': 'Redeem card and receive balance',
  'screens_scan_card_screen.022':
      'You can only scan the card. Receiving the balance requires account verification.',
  'screens_scan_card_screen.023': 'Barcode',
  'screens_scan_card_screen.024': 'Card type',
  'screens_scan_card_screen.025': 'Visibility',
  'screens_scan_card_screen.026': 'Card value',
  'screens_scan_card_screen.027': 'Issue cost',
  'screens_scan_card_screen.028': 'Owner',
  'screens_scan_card_screen.029': 'Issued by',
  'screens_scan_card_screen.030': 'Used by',
  'screens_scan_card_screen.031': 'Customer name',
  'screens_scan_card_screen.032': 'Issue date',
  'screens_scan_card_screen.033': 'Usage date',
  'screens_scan_card_screen.034': 'Last resale',
  'screens_scan_card_screen.035': 'Usage count',
  'screens_scan_card_screen.036': 'Resale count',
  'screens_scan_card_screen.037': 'Total redeemed value',
  'screens_scan_card_screen.038': 'Allowed users',
  'screens_scan_card_screen.039': 'Scan failed',
  'screens_scan_card_screen.040': 'The card could not be found.',
  'screens_scan_card_screen.041':
      'Point the camera at the card and the code will be captured automatically.',
  'screens_scan_card_screen.042':
      'If it is not captured automatically, move the card closer to the frame.',
  'screens_scan_card_screen.043': 'Unavailable',
  'screens_scan_card_screen.044': 'Redeemed',
  'screens_scan_card_screen.045':
      'The card was redeemed and the balance was added successfully.',
  'screens_scan_card_screen.046': 'Could not complete action',
  'screens_scan_card_screen.047':
      'You do not have permission to reactivate used cards.',
  'screens_scan_card_screen.048': 'Confirm reactivation',
  'screens_scan_card_screen.049':
      'This card will be reactivated so it can be used again. Do you want to continue?',
  'screens_scan_card_screen.050': 'Cancel',
  'screens_scan_card_screen.051': 'Card reactivated',
  'screens_scan_card_screen.052':
      'The card was reactivated successfully and is ready to use.',
  'screens_scan_card_screen.053': 'Used',
  'screens_scan_card_screen.054': 'Archived',
  'screens_scan_card_screen.055': 'Available',
  'screens_scan_card_screen.056': 'Single use',
  'screens_scan_card_screen.057': 'Balance',
  'screens_scan_card_screen.058': 'Private',
  'screens_scan_card_screen.059': 'Public',
  'screens_scan_card_screen.065': 'Location specific',
  'screens_scan_card_screen.066': 'Private financial',
  'screens_scan_card_screen.067': 'Public financial',
  'screens_scan_card_screen.060': 'User',
  'screens_card_print_requests_screen.001': 'Unable to load requests',
  'screens_card_print_requests_screen.002': 'Incomplete data',
  'screens_card_print_requests_screen.003':
      'Enter a valid card value and quantity.',
  'screens_card_print_requests_screen.004': 'Request sent',
  'screens_card_print_requests_screen.005':
      'Your card print request was sent successfully.',
  'screens_card_print_requests_screen.006': 'Unable to send request',
  'screens_card_print_requests_screen.007': 'Card print request',
  'screens_card_print_requests_screen.008': 'Card type',
  'screens_card_print_requests_screen.009': 'Standard balance cards',
  'screens_card_print_requests_screen.010': 'Single-use cards',
  'screens_card_print_requests_screen.011':
      'Value is fixed for single-use cards',
  'screens_card_print_requests_screen.012': 'Card value',
  'screens_card_print_requests_screen.013': 'Number of cards',
  'screens_card_print_requests_screen.014': 'Additional notes',
  'screens_card_print_requests_screen.015': 'Cancel',
  'screens_card_print_requests_screen.016': 'Sending...',
  'screens_card_print_requests_screen.017': 'Send request',
  'screens_card_print_requests_screen.018': 'Card Print Requests',
  'screens_card_print_requests_screen.019':
      'Submit your request here. The amount is deducted directly from your balance, then the admin follows the review, printing, and preparation stages until completion.',
  'screens_card_print_requests_screen.020': 'Printable balance',
  'screens_card_print_requests_screen.021': 'Print request fee',
  'screens_card_print_requests_screen.022': 'Default',
  'screens_card_print_requests_screen.023': 'New print request',
  'screens_card_print_requests_screen.024':
      'There are no previous print requests yet.',
  'screens_card_print_requests_screen.025': 'Pending review',
  'screens_card_print_requests_screen.026': 'Type',
  'screens_card_print_requests_screen.027': 'Single use',
  'screens_card_print_requests_screen.028': 'Standard cards',
  'screens_card_print_requests_screen.029': 'Quantity',
  'screens_card_print_requests_screen.030': '{count} cards',
  'screens_card_print_requests_screen.031': 'Value',
  'screens_card_print_requests_screen.032': 'Total',
  'screens_card_print_requests_screen.033': 'Your notes: {notes}',
  'screens_card_print_requests_screen.034': 'Admin notes: {notes}',
  'screens_card_print_requests_screen.035': 'Review',
  'screens_card_print_requests_screen.036': 'Approved',
  'screens_card_print_requests_screen.037': 'Printing',
  'screens_card_print_requests_screen.038': 'Ready',
  'screens_card_print_requests_screen.039': 'Completed',
  'screens_card_print_requests_screen.040': 'Rejected',
  'screens_create_card_screen.001': 'Shwakel',
  'screens_create_card_screen.002': 'Balance card',
  'screens_create_card_screen.003': 'Single-use card',
  'screens_create_card_screen.004': 'Incomplete data',
  'screens_create_card_screen.005':
      'Please enter valid issuance data before continuing.',
  'screens_create_card_screen.006': 'Private card',
  'screens_create_card_screen.007':
      'Choose at least one user to create a private card.',
  'screens_create_card_screen.008': 'Single use',
  'screens_create_card_screen.009': 'Balance',
  'screens_create_card_screen.010': 'Private',
  'screens_create_card_screen.011': 'Public',
  'screens_create_card_screen.012': 'No monetary value',
  'screens_create_card_screen.013': 'Confirm card issuance',
  'screens_create_card_screen.014':
      'You are about to issue {quantity} cards.\nType: {type}\nVisibility: {visibility}\nValue: {value}\n{privateLine}',
  'screens_create_card_screen.015': 'Selected beneficiaries: {count}',
  'screens_create_card_screen.016': 'Cancel',
  'screens_create_card_screen.017': 'Issue now',
  'screens_create_card_screen.018': 'Unable to issue cards',
  'screens_create_card_screen.019': 'Valid for circulation',
  'screens_create_card_screen.020': 'Issued successfully',
  'screens_create_card_screen.021':
      'Created {count} cards successfully. Do you want to send them to print now?',
  'screens_create_card_screen.022': 'Later',
  'screens_create_card_screen.023': 'Start printing',
  'screens_create_card_screen.024': 'Choose private-card beneficiaries',
  'screens_create_card_screen.025': 'Search by username or number',
  'screens_create_card_screen.026': 'User',
  'screens_create_card_screen.027': 'ID: {id}',
  'screens_create_card_screen.028': 'Confirm',
  'screens_create_card_screen.029': 'Issue new cards',
  'screens_create_card_screen.030':
      'Issue digital cards with a polished layout',
  'screens_create_card_screen.031':
      'Set the value, quantity, and card type, then customize the title, stamp, and logo before sending the batch to print.',
  'screens_create_card_screen.032': 'Issuance details',
  'screens_create_card_screen.033':
      'Choose the type, quantity, and value, then define the card visibility scope.',
  'screens_create_card_screen.034': 'Card type',
  'screens_create_card_screen.035': 'Card value (?)',
  'screens_create_card_screen.036':
      'A single-use card does not need a monetary value, and its type will appear clearly in print.',
  'screens_create_card_screen.037': 'Number of cards',
  'screens_create_card_screen.038': 'Card visibility',
  'screens_create_card_screen.039': 'Private card beneficiaries',
  'screens_create_card_screen.040':
      'These cards will only appear for the users you choose here.',
  'screens_create_card_screen.041': 'Select users',
  'screens_create_card_screen.042': 'Edit users',
  'screens_create_card_screen.043': 'Generate and issue batch',
  'screens_create_card_screen.044': 'Print customization',
  'screens_create_card_screen.045':
      'Enable the title, stamp, and custom logo before printing, with lighter text sizing for a cleaner card layout.',
  'screens_create_card_screen.046': 'Card title',
  'screens_create_card_screen.047': 'Stamp text',
  'screens_create_card_screen.048': 'Show logo',
  'screens_create_card_screen.049':
      'The uploaded account logo will be used when enabled',
  'screens_create_card_screen.050': 'The default app logo will be used',
  'screens_create_card_screen.051': 'Use account logo',
  'screens_create_card_screen.052':
      'You can change the logo from account settings when needed',
  'screens_create_card_screen.053': 'Show stamp',
  'screens_create_card_screen.054':
      'Displayed in a lighter, smaller style to keep the design balanced',
  'screens_create_card_screen.055': 'Entry or pickup card',
  'screens_create_card_screen.056': 'Digital card for internal use',
  'screens_create_card_screen.057': 'Private card',
  'screens_create_card_screen.058': 'Public card',
  'screens_create_card_screen.059': 'Smaller, cleaner text',
  'screens_create_card_screen.060': 'Latest issuance',
  'screens_create_card_screen.061': 'Number of cards',
  'screens_create_card_screen.062': '{count} cards',
  'screens_create_card_screen.063': 'Visibility type',
  'screens_create_card_screen.064': 'Single-card value',
  'screens_create_card_screen.065': 'Reprint batch',
  'screens_contact_us_screen.001': 'Support WhatsApp',
  'screens_contact_us_screen.002': 'Official email',
  'screens_contact_us_screen.003': 'Head office',
  'screens_contact_us_screen.004': 'Working hours: 9:00 AM - 9:00 PM',
  'screens_contact_us_screen.005':
      'We are ready to serve you throughout the week, except official holidays.',
  'screens_contact_us_screen.006': 'Shwakel Help Center',
  'screens_contact_us_screen.007':
      'Our team is ready to answer your questions and resolve technical issues as quickly as possible.',
  'widgets_admin_summary_widgets.001': 'Metric',
  'widgets_admin_summary_widgets.002': 'Total balances',
  'widgets_admin_summary_widgets.003': 'Customers',
  'widgets_admin_summary_widgets.004': 'Printing debt',
  'widgets_admin_summary_widgets.005': 'Administrators',
  'widgets_admin_withdrawal_request_card.001': 'Not specified',
  'widgets_admin_withdrawal_request_card.002': 'No details available',
  'widgets_admin_withdrawal_request_card.003': 'Withdrawal request: {date}',
  'widgets_admin_withdrawal_request_card.004': 'Approve request',
  'widgets_admin_withdrawal_request_card.005': 'Reject',
  'screens_admin_dashboard_screen.003': 'Administration',
  'screens_admin_dashboard_screen.004': 'Card print requests',
  'screens_admin_dashboard_screen.005':
      'Review the request, then start printing, preparation, and completion.',
  'screens_admin_dashboard_screen.006': 'Customer management',
  'screens_admin_dashboard_screen.007':
      'Search customers, open their profiles, and add a new user.',
  'screens_admin_dashboard_screen.008': 'Device requests',
  'screens_admin_dashboard_screen.009':
      'Review newly linked device requests only.',
  'screens_admin_dashboard_screen.010': 'Withdrawal requests',
  'screens_admin_dashboard_screen.011':
      'Approve or reject withdrawal requests from a dedicated screen.',
  'screens_admin_dashboard_screen.012': 'Top-up requests',
  'screens_admin_dashboard_screen.013':
      'Review top-up requests and approve or reject them quickly.',
  'screens_admin_dashboard_screen.014': 'Branches and locations',
  'screens_admin_dashboard_screen.015':
      'Manage supported branches and locations without loading other data.',
  'screens_admin_dashboard_screen.016': 'System settings',
  'screens_admin_dashboard_screen.017':
      'Registration, support, policies, and top-up methods.',
  'screens_admin_dashboard_screen.018': 'Permission templates',
  'screens_admin_dashboard_screen.019':
      'Control what each membership level can view and use.',
  'screens_quick_transfer_screen.023':
      'Enter a phone number to find the recipient.',
  'screens_quick_transfer_screen.024': 'Could not find the user',
  'screens_quick_transfer_screen.025':
      'Could not determine the recipient account.',
  'screens_quick_transfer_screen.026':
      'The balance was sent successfully to the recipient.',
  'screens_quick_transfer_screen.027': 'Amount to transfer (ILS)',
  'screens_quick_transfer_screen.028':
      'You do not have permission to use quick transfer.',
  'screens_quick_transfer_screen.029': 'Send balance by phone number',
  'screens_quick_transfer_screen.030':
      'Enter only the recipient phone number, then review basic details without showing any financial information.',
  'screens_quick_transfer_screen.031': 'Recipient phone number',
  'screens_quick_transfer_screen.032':
      'For privacy reasons, the recipient balance is not displayed.',
  'screens_quick_transfer_screen.033': 'Send balance to this number',
  'screens_quick_transfer_screen.034':
      'You can also scan the recipient code to complete the transfer faster.',
  'screens_quick_transfer_screen.035':
      'Show this code to the sender so they can transfer balance to you directly.',
  'screens_admin_card_print_requests_screen.029': 'Archive',
  'screens_admin_card_print_requests_screen.030': 'Completed',
  'screens_admin_card_print_requests_screen.031': 'Source',
  'screens_admin_card_print_requests_screen.032': 'Print count',
  'screens_admin_card_print_requests_screen.033': 'Last printed',
  'screens_admin_card_print_requests_screen.034': 'Local',
  'screens_admin_card_print_requests_screen.035': 'From app',
  'screens_admin_card_print_requests_screen.036': 'Not printed yet',
  'screens_admin_permissions_screen.042': 'Offline card scan',
  'screens_admin_permissions_screen.043': 'Manage sub-users',
  'screens_admin_customer_screen.072': 'Offline card scan',
  'screens_scan_card_screen.061': 'Offline scan',
  'screens_scan_card_screen.062':
      'Loaded the card from local cache and will sync when connected.',
  'screens_scan_card_screen.063': 'Saved offline',
  'screens_scan_card_screen.064':
      'The scan will sync once internet is available.',
  'screens_card_print_requests_screen.041': 'Printing limit exceeded',
  'screens_card_print_requests_screen.042':
      'Available balance {available} is lower than total {total}. Printing fee {fee}%.\nTo print higher amounts, contact us at {phone}.',
  'screens_card_print_requests_screen.043': 'OK',
  'screens_card_print_requests_screen.044': 'Source',
  'screens_card_print_requests_screen.045': 'Local',
  'screens_card_print_requests_screen.046': 'From app',
  'screens_card_print_requests_screen.047': 'Last printed',
  'screens_card_print_requests_screen.048': 'Not printed yet',
};
